<?php
/**
 * CI/CD API - Push Workflow to Client Repository
 * Automatically pushes deploy.yml to .github/workflows/ in client repos
 * 
 * POST /api/push-workflow.php
 * - Reads template from cicd/templates/deploy.yml
 * - Pushes to client repo via GitHub API
 * - Creates .github/workflows/ directory if needed
 */

define('CICD_API', true);
require_once __DIR__ . '/config.php';

header('Access-Control-Allow-Origin: *');
header('Access-Control-Allow-Methods: POST, OPTIONS');
header('Access-Control-Allow-Headers: Content-Type, Authorization');
header('Content-Type: application/json');

if ($_SERVER['REQUEST_METHOD'] === 'OPTIONS') {
    exit(0);
}

// Get GitHub token
function getGitHubToken() {
    $token_file = '/home/retaillogimaxind/.github_token';
    if (file_exists($token_file)) {
        return trim(file_get_contents($token_file));
    }
    return null;
}

// Get file content from GitHub (to check if exists and get SHA)
function getFileFromGitHub($org, $repo, $path, $token) {
    $url = "https://api.github.com/repos/$org/$repo/contents/$path";
    
    $ch = curl_init($url);
    curl_setopt_array($ch, [
        CURLOPT_RETURNTRANSFER => true,
        CURLOPT_HTTPHEADER => [
            'Accept: application/vnd.github.v3+json',
            "Authorization: Bearer $token",
            'User-Agent: Logimax-CICD'
        ]
    ]);
    $response = curl_exec($ch);
    $http_code = curl_getinfo($ch, CURLINFO_HTTP_CODE);
    curl_close($ch);
    
    if ($http_code === 200) {
        return json_decode($response, true);
    }
    return null;
}

// Create or update file in GitHub repo
function pushFileToGitHub($org, $repo, $path, $content, $message, $token, $sha = null) {
    $url = "https://api.github.com/repos/$org/$repo/contents/$path";
    
    $data = [
        'message' => $message,
        'content' => base64_encode($content),
        'branch' => 'main' // Default branch for workflow files
    ];
    
    if ($sha) {
        $data['sha'] = $sha; // Required for updates
    }
    
    $ch = curl_init($url);
    curl_setopt_array($ch, [
        CURLOPT_RETURNTRANSFER => true,
        CURLOPT_CUSTOMREQUEST => 'PUT',
        CURLOPT_POSTFIELDS => json_encode($data),
        CURLOPT_HTTPHEADER => [
            'Accept: application/vnd.github.v3+json',
            "Authorization: Bearer $token",
            'User-Agent: Logimax-CICD',
            'Content-Type: application/json'
        ]
    ]);
    $response = curl_exec($ch);
    $http_code = curl_getinfo($ch, CURLINFO_HTTP_CODE);
    curl_close($ch);
    
    return [
        'success' => ($http_code === 200 || $http_code === 201),
        'http_code' => $http_code,
        'response' => json_decode($response, true)
    ];
}

// Generate client-specific workflow content
function generateWorkflowContent($clientName, $useWebhook = true) {
    // Read template
    $templatePath = __DIR__ . '/../../templates/deploy.yml';
    
    if (!file_exists($templatePath)) {
        return null;
    }
    
    $content = file_get_contents($templatePath);
    
    // Add header comment with client name
    $header = "# =============================================================================
# AUTO-GENERATED WORKFLOW FOR: $clientName
# Generated by Logimax CI/CD Dashboard
# DO NOT EDIT MANUALLY - Changes may be overwritten
# =============================================================================

";
    
    return $header . $content;
}

try {
    if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
        jsonResponse(['error' => 'Method not allowed'], 405);
    }
    
    $input = json_decode(file_get_contents('php://input'), true);
    
    // Validate required fields
    $org = $input['org'] ?? 'LOGIMAX-CLIENTS';
    $repo = $input['repo'] ?? null;
    $clientName = $input['client_name'] ?? $repo;
    
    if (!$repo) {
        jsonResponse(['error' => 'Repository name required'], 400);
    }
    
    // Get GitHub token
    $token = getGitHubToken();
    if (!$token) {
        jsonResponse([
            'success' => false,
            'error' => 'GitHub token not configured',
            'manual_setup' => true,
            'instructions' => [
                '1. Download the workflow template from: cicd/templates/deploy.yml',
                '2. Create .github/workflows/ folder in your client repo',
                '3. Copy deploy.yml to .github/workflows/deploy.yml',
                '4. Commit and push to main branch'
            ]
        ]);
    }
    
    // Generate workflow content
    $workflowContent = generateWorkflowContent($clientName);
    if (!$workflowContent) {
        jsonResponse(['error' => 'Workflow template not found'], 500);
    }
    
    $workflowPath = '.github/workflows/deploy.yml';
    
    // Check if file already exists (to get SHA for update)
    $existing = getFileFromGitHub($org, $repo, $workflowPath, $token);
    $sha = $existing ? $existing['sha'] : null;
    $action = $sha ? 'Updated' : 'Created';
    
    // Push workflow file
    $result = pushFileToGitHub(
        $org, 
        $repo, 
        $workflowPath,
        $workflowContent,
        "🚀 $action CI/CD workflow via dashboard",
        $token,
        $sha
    );
    
    if ($result['success']) {
        // Update client status in database if we have the client
        global $pdo;
        if ($pdo) {
            $stmt = $pdo->prepare("UPDATE cicd_clients SET status = 'active' WHERE repo_name LIKE ?");
            $stmt->execute(["%$repo%"]);
        }
        
        jsonResponse([
            'success' => true,
            'message' => "$action workflow file successfully",
            'action' => strtolower($action),
            'path' => $workflowPath,
            'repo' => "$org/$repo",
            'url' => "https://github.com/$org/$repo/blob/main/$workflowPath"
        ]);
    } else {
        // Return manual instructions if API fails
        jsonResponse([
            'success' => false,
            'error' => 'Failed to push workflow file',
            'http_code' => $result['http_code'],
            'manual_setup' => true,
            'template_url' => 'cicd/templates/deploy.yml',
            'target_path' => $workflowPath,
            'instructions' => [
                '1. Download the workflow template',
                '2. Create .github/workflows/ folder in your client repo',
                '3. Copy deploy.yml to .github/workflows/deploy.yml',
                '4. Commit and push to main branch'
            ]
        ], 500);
    }
    
} catch (Exception $e) {
    jsonResponse(['error' => $e->getMessage()], 500);
}
