-- ============================================================
-- Patch: Change grn_type = 2 to grn_type = 4 in ret_view_smith_ledger
-- Date: 2026-04-08
-- Purpose: Smith ledger should only show grn_type = 4 records
--          in purchase receipt and purchase return subqueries
-- Affected: 3 places (1st, 6th, 7th UNION subqueries)
-- ============================================================

DROP VIEW IF EXISTS `ret_view_smith_ledger`;

CREATE 
VIEW `ret_view_smith_ledger` AS

-- UNION 1: Purchase Receipt Items (grn_type changed from 2 to 4)
select `pd`.`design_name` AS `category`,`pr`.`product_name` AS `product`,`po`.`po_date` AS `trans_date`,`po`.`po_ref_no` AS `referenceno`,1 AS `trans_type`,`pitm`.`po_order_no` AS `trans_id`,sum(if((ifnull(`uom`.`divided_by_value`,0) = 0),`pitm`.`gross_wt`,round((`pitm`.`gross_wt` / `uom`.`divided_by_value`),3))) AS `gross_wt`,sum(if((ifnull(`uom`.`divided_by_value`,0) = 0),`pitm`.`net_wt`,round((`pitm`.`net_wt` / `uom`.`divided_by_value`),3))) AS `net_wt`,sum(`pitm`.`no_of_pcs`) AS `no_of_pcs`,`pitm`.`purchase_touch` AS `purchase_touch`,sum(`pitm`.`item_pure_wt`) AS `purewt`,`po`.`po_karigar_id` AS `customer_id`,1 AS `trans_rec_type`,((ifnull(`pochr`.`charge`,0) + ifnull(`post`.`stamount`,0)) + if((`pitm`.`mc_type` = 1),(`pitm`.`mc_value` * `pitm`.`gross_wt`),(`pitm`.`mc_value` * `pitm`.`no_of_pcs`))) AS `trans_amount`,`pitm`.`po_item_cat_id` AS `catid`,`pr`.`stone_type` AS `stone_type`,`pitm`.`po_item_pro_id` AS `proid`,1 AS `trans_screen_id`,`met`.`id_metal` AS `id_metal`,`met`.`metal` AS `metal`,'' AS `rate`,ifnull(`pitm`.`remark`,'') AS `narration`,unix_timestamp(`po`.`po_date`) AS `unixtransdate`,`uom`.`uom_short_code` AS `dispuom` from ((((((((((`ret_purchase_order_items` `pitm` left join `ret_purchase_order` `po` on((`po`.`po_id` = `pitm`.`po_item_po_id`))) left join `ret_grn_entry` `grn` on((`grn`.`grn_id` = `po`.`po_grn_id`))) left join `ret_karigar` `kr` on((`kr`.`id_karigar` = `po`.`po_karigar_id`))) left join `ret_category` `cat` on((`cat`.`id_ret_category` = `pitm`.`po_item_cat_id`))) left join `metal` `met` on((`met`.`id_metal` = `cat`.`id_metal`))) left join `ret_product_master` `pr` on((`pr`.`pro_id` = `pitm`.`po_item_pro_id`))) left join `ret_design_master` `pd` on((`pd`.`design_no` = `pitm`.`po_item_des_id`))) left join `ret_uom` `uom` on((`uom`.`uom_id` = `pitm`.`uom`))) left join (select sum(`ret_purchase_other_charges`.`total_charge_value`) AS `charge`,`ret_purchase_other_charges`.`pur_po_item_id` AS `pur_po_item_id` from `ret_purchase_other_charges` group by `ret_purchase_other_charges`.`pur_po_item_id`) `pochr` on((`pochr`.`pur_po_item_id` = `pitm`.`po_item_id`))) left join (select sum(`ret_po_stone_items`.`po_stone_amount`) AS `stamount`,`ret_po_stone_items`.`po_item_id` AS `po_item_id` from `ret_po_stone_items` group by `ret_po_stone_items`.`po_item_id`) `post` on((`post`.`po_item_id` = `pitm`.`po_item_id`)))
where ((`grn`.`grn_type` = 4) and (`po`.`is_approved` = 1) and (`po`.`bill_status` = 1))
group by `pitm`.`po_item_id`

-- UNION 2: Stone Items
union select `pd`.`design_name` AS `category`,`pr`.`product_name` AS `product`,`po`.`po_date` AS `trans_date`,`iss`.`met_issue_ref_id` AS `referenceno`,1 AS `trans_type`,`pitm`.`po_order_no` AS `trans_id`,sum(if((ifnull(`uom`.`divided_by_value`,0) = 0),`posi`.`po_stone_wt`,round((`posi`.`po_stone_wt` / `uom`.`divided_by_value`),3))) AS `gross_wt`,sum(if((ifnull(`uom`.`divided_by_value`,0) = 0),`posi`.`po_stone_wt`,round((`posi`.`po_stone_wt` / `uom`.`divided_by_value`),3))) AS `net_wt`,sum(`posi`.`po_stone_pcs`) AS `no_of_pcs`,'' AS `purchase_touch`,'' AS `purewt`,`iss`.`met_issue_karid` AS `customer_id`,1 AS `trans_rec_type`,0 AS `trans_amount`,`pitm`.`po_item_cat_id` AS `catid`,`pr`.`stone_type` AS `stone_type`,`pitm`.`po_item_pro_id` AS `proid`,1 AS `trans_screen_id`,`met`.`id_metal` AS `id_metal`,`met`.`metal` AS `metal`,'' AS `rate`,ifnull(`pitm`.`remark`,'') AS `narration`,unix_timestamp(`po`.`po_date`) AS `unixtransdate`,`uom`.`uom_short_code` AS `dispuom` from ((((((((((`ret_po_stone_items` `posi` left join `ret_karigar_metal_issue_details` `iitm` on((`iitm`.`issue_met_id` = `posi`.`issue_met_id`))) left join `ret_karigar_metal_issue` `iss` on((`iss`.`met_issue_id` = `iitm`.`issue_met_parent_id`))) left join `ret_karigar` `kr` on((`kr`.`id_karigar` = `iss`.`met_issue_karid`))) left join `ret_category` `cat` on((`cat`.`id_ret_category` = `iitm`.`issue_cat_id`))) left join `metal` `met` on((`met`.`id_metal` = `cat`.`id_metal`))) left join `ret_product_master` `pr` on((`pr`.`pro_id` = `iitm`.`issu_met_pro_id`))) left join `ret_design_master` `pd` on((`pd`.`design_no` = `iitm`.`issu_met_id_design`))) left join `ret_uom` `uom` on((`uom`.`uom_id` = `posi`.`po_stone_uom`))) left join `ret_purchase_order_items` `pitm` on((`pitm`.`po_item_id` = `posi`.`po_item_id`))) left join `ret_purchase_order` `po` on((`po`.`po_id` = `pitm`.`po_item_po_id`)))
where ((`posi`.`issue_met_id` is not null) and (`po`.`bill_status` = 1))
group by `posi`.`po_st_id`

-- UNION 3: Purchase Order Items with issue_met_id
union select `pd`.`design_name` AS `category`,`pr`.`product_name` AS `product`,`po`.`po_date` AS `trans_date`,`po`.`po_ref_no` AS `referenceno`,1 AS `trans_type`,`pitm`.`po_order_no` AS `trans_id`,sum(if((ifnull(`uom`.`divided_by_value`,0) = 0),`pitm`.`gross_wt`,round((`pitm`.`gross_wt` / `uom`.`divided_by_value`),3))) AS `gross_wt`,sum(if((ifnull(`uom`.`divided_by_value`,0) = 0),`pitm`.`net_wt`,round((`pitm`.`net_wt` / `uom`.`divided_by_value`),3))) AS `net_wt`,sum(`pitm`.`no_of_pcs`) AS `no_of_pcs`,'' AS `purchase_touch`,'' AS `purewt`,`iss`.`met_issue_karid` AS `customer_id`,1 AS `trans_rec_type`,0 AS `trans_amount`,`pitm`.`po_item_cat_id` AS `catid`,`pr`.`stone_type` AS `stone_type`,`pitm`.`po_item_pro_id` AS `proid`,1 AS `trans_screen_id`,`met`.`id_metal` AS `id_metal`,`met`.`metal` AS `metal`,'' AS `rate`,ifnull(`pitm`.`remark`,'') AS `narration`,unix_timestamp(`po`.`po_date`) AS `unixtransdate`,`uom`.`uom_short_code` AS `dispuom` from (((((((((`ret_purchase_order_items` `pitm` left join `ret_karigar_metal_issue_details` `iitm` on((`iitm`.`issue_met_id` = `pitm`.`issue_met_id`))) left join `ret_karigar_metal_issue` `iss` on((`iss`.`met_issue_id` = `iitm`.`issue_met_parent_id`))) left join `ret_karigar` `kr` on((`kr`.`id_karigar` = `iss`.`met_issue_karid`))) left join `ret_category` `cat` on((`cat`.`id_ret_category` = `iitm`.`issue_cat_id`))) left join `metal` `met` on((`met`.`id_metal` = `cat`.`id_metal`))) left join `ret_product_master` `pr` on((`pr`.`pro_id` = `iitm`.`issu_met_pro_id`))) left join `ret_design_master` `pd` on((`pd`.`design_no` = `iitm`.`issu_met_id_design`))) left join `ret_uom` `uom` on((`uom`.`uom_id` = `pitm`.`uom`))) left join `ret_purchase_order` `po` on((`po`.`po_id` = `pitm`.`po_item_po_id`)))
where ((`pitm`.`issue_met_id` is not null) and (`po`.`bill_status` = 1))
group by `pitm`.`po_item_id`

-- UNION 4: Metal Issue Details
union select `pd`.`design_name` AS `category`,`pr`.`product_name` AS `product`,`iss`.`met_issue_date` AS `trans_date`,`iss`.`met_issue_ref_id` AS `referenceno`,2 AS `trans_type`,`iitm`.`issue_met_parent_id` AS `trans_id`,if((`cat`.`cat_type` = 2),0,if((ifnull(`uom`.`divided_by_value`,0) = 0),`iitm`.`issue_metal_wt`,round((`iitm`.`issue_metal_wt` / `uom`.`divided_by_value`),3))) AS `gross_wt`,if((`cat`.`cat_type` = 2),0,if((ifnull(`uom`.`divided_by_value`,0) = 0),`iitm`.`issue_metal_wt`,round((`iitm`.`issue_metal_wt` / `uom`.`divided_by_value`),3))) AS `net_wt`,ifnull(`iitm`.`issue_pcs`,1) AS `no_of_pcs`,'100' AS `purchase_touch`,if((`pr`.`stone_type` = 0),`iitm`.`issue_metal_pur_wt`,if((ifnull(`uom`.`divided_by_value`,0) = 0),`iitm`.`issue_metal_wt`,round((`iitm`.`issue_metal_wt` / `uom`.`divided_by_value`),3))) AS `purewt`,`iss`.`met_issue_karid` AS `customer_id`,1 AS `trans_rec_type`,0 AS `trans_amount`,`iitm`.`issue_cat_id` AS `catid`,`pr`.`stone_type` AS `stone_type`,`iitm`.`issu_met_pro_id` AS `proid`,2 AS `trans_screen_id`,`met`.`id_metal` AS `id_metal`,`met`.`metal` AS `metal`,'' AS `rate`,'' AS `narration`,unix_timestamp(`iss`.`met_issue_date`) AS `unixtransdate`,`uom`.`uom_short_code` AS `dispuom` from (((((((`ret_karigar_metal_issue_details` `iitm` left join `ret_karigar_metal_issue` `iss` on((`iss`.`met_issue_id` = `iitm`.`issue_met_parent_id`))) left join `ret_karigar` `kr` on((`kr`.`id_karigar` = `iss`.`met_issue_karid`))) left join `ret_category` `cat` on((`cat`.`id_ret_category` = `iitm`.`issue_cat_id`))) left join `metal` `met` on((`met`.`id_metal` = `cat`.`id_metal`))) left join `ret_product_master` `pr` on((`pr`.`pro_id` = `iitm`.`issu_met_pro_id`))) left join `ret_design_master` `pd` on((`pd`.`design_no` = `iitm`.`issu_met_id_design`))) left join `ret_uom` `uom` on((`uom`.`uom_id` = `iitm`.`issue_uom_id`)))
where (((`kr`.`karigar_for` = 1) or (`kr`.`karigar_for` = 5)) and (`iss`.`bill_status` = 1))
group by `iitm`.`issue_cat_id`,`iitm`.`issu_met_pro_id`,`iitm`.`issue_met_parent_id`

-- UNION 5: Payment
union select 'PAYMENT' AS `category`,'' AS `product`,`pay`.`pay_create_on` AS `trans_date`,`pay`.`pay_refno` AS `referenceno`,2 AS `trans_type`,`pay`.`pay_id` AS `trans_id`,0 AS `gross_wt`,0 AS `net_wt`,0 AS `no_of_pcs`,'' AS `purchase_touch`,0 AS `purewt`,`pay`.`pay_sup_id` AS `customer_id`,2 AS `trans_rec_type`,sum(`pd`.`payment_amount`) AS `trans_amount`,'' AS `catid`,0 AS `stone_type`,'' AS `proid`,3 AS `trans_screen_id`,'' AS `id_metal`,'' AS `metal`,'' AS `rate`,'' AS `narration`,unix_timestamp(`pay`.`pay_create_on`) AS `unixtransdate`,'' AS `dispuom` from (`ret_po_payment` `pay` left join `ret_po_payment_detail` `pd` on((`pd`.`pay_id` = `pay`.`pay_id`)))
where ((`pay`.`pay_status` = 1) and (`pay`.`bill_type` = 2))
group by `pay`.`pay_id`

-- UNION 6: Purchase Return with purchase_type = 0 (grn_type changed from 2 to 4)
union select `pd`.`design_name` AS `category`,`pr`.`product_name` AS `product`,`ret`.`bill_date` AS `trans_date`,`ret`.`pur_ret_ref_no` AS `referenceno`,2 AS `trans_type`,`ret`.`pur_return_id` AS `trans_id`,sum(`pret`.`pur_ret_gwt`) AS `gross_wt`,sum(`pret`.`pur_ret_nwt`) AS `net_wt`,sum(`pret`.`pur_ret_pcs`) AS `no_of_pcs`,`pret`.`pur_ret_purchase_touch` AS `purchase_touch`,sum(`pret`.`pur_ret_pur_wt`) AS `purewt`,`ret`.`pur_ret_supplier_id` AS `customer_id`,1 AS `trans_rec_type`,sum(`pret`.`pur_ret_debit_note_amt`) AS `trans_amount`,`cat`.`id_ret_category` AS `catid`,`pr`.`stone_type` AS `stone_type`,`pret`.`id_product` AS `proid`,5 AS `trans_screen_id`,`met`.`id_metal` AS `id_metal`,`met`.`metal` AS `metal`,'' AS `rate`,'' AS `narration`,unix_timestamp(`ret`.`bill_date`) AS `unixtransdate`,'' AS `dispuom` from (((((((((((`ret_purchase_return_items` `pret` left join `ret_purchase_return` `ret` on((`ret`.`pur_return_id` = `pret`.`pur_ret_id`))) left join (select sum(`ret_purchase_return_other_charges`.`total_charge_value`) AS `charges`,`ret_purchase_return_other_charges`.`pur_ret_itm_id` AS `pur_ret_itm_id` from `ret_purchase_return_other_charges` group by `ret_purchase_return_other_charges`.`pur_ret_itm_id`) `retchr` on((`retchr`.`pur_ret_itm_id` = `pret`.`pur_ret_itm_id`))) left join (select sum(`ret_purchase_return_stone_items`.`ret_stone_amount`) AS `stamount`,`ret_purchase_return_stone_items`.`pur_ret_return_id` AS `pur_ret_return_id` from `ret_purchase_return_stone_items` group by `ret_purchase_return_stone_items`.`pur_ret_return_id`) `retst` on((`retst`.`pur_ret_return_id` = `pret`.`pur_ret_itm_id`))) left join `ret_purchase_order_items` `pitm` on((`pitm`.`po_item_id` = `pret`.`pur_ret_po_item_id`))) left join `ret_purchase_order` `po` on((`po`.`po_id` = `pitm`.`po_item_po_id`))) left join `ret_grn_entry` `grn` on((`grn`.`grn_id` = `po`.`po_grn_id`))) left join `ret_karigar` `kr` on((`kr`.`id_karigar` = `ret`.`pur_ret_supplier_id`))) left join `ret_product_master` `pr` on((`pr`.`pro_id` = `pret`.`id_product`))) left join `ret_design_master` `pd` on((`pd`.`design_no` = `pret`.`id_design`))) left join `ret_category` `cat` on((`cat`.`id_ret_category` = `pr`.`cat_id`))) left join `metal` `met` on((`met`.`id_metal` = `cat`.`id_metal`)))
where ((`ret`.`pur_ret_convert_to` = 2) and (`ret`.`purchase_type` = 0) and (`grn`.`grn_type` = 4) and (`ret`.`bill_status` = 1))
group by `pret`.`pur_ret_itm_id`

-- UNION 7: Purchase Return without purchase_type (grn_type changed from 2 to 4)
union select `pd`.`design_name` AS `category`,`pr`.`product_name` AS `product`,`ret`.`bill_date` AS `trans_date`,`ret`.`pur_ret_ref_no` AS `referenceno`,2 AS `trans_type`,`ret`.`pur_return_id` AS `trans_id`,sum(`pret`.`pur_ret_gwt`) AS `gross_wt`,sum(`pret`.`pur_ret_nwt`) AS `net_wt`,sum(`pret`.`pur_ret_pcs`) AS `no_of_pcs`,`pret`.`pur_ret_purchase_touch` AS `purchase_touch`,sum(`pret`.`pur_ret_pur_wt`) AS `purewt`,`ret`.`pur_ret_supplier_id` AS `customer_id`,1 AS `trans_rec_type`,sum(`pret`.`pur_ret_debit_note_amt`) AS `trans_amount`,`cat`.`id_ret_category` AS `catid`,`pr`.`stone_type` AS `stone_type`,`pret`.`id_product` AS `proid`,5 AS `trans_screen_id`,`met`.`id_metal` AS `id_metal`,`met`.`metal` AS `metal`,'' AS `rate`,'' AS `narration`,unix_timestamp(`ret`.`bill_date`) AS `unixtransdate`,'' AS `dispuom` from (((((((((((`ret_purchase_return_items` `pret` left join `ret_purchase_return` `ret` on((`ret`.`pur_return_id` = `pret`.`pur_ret_id`))) left join `ret_purchase_order_items` `pitm` on((`pitm`.`po_item_id` = `pret`.`pur_ret_po_item_id`))) left join (select sum(`ret_purchase_return_other_charges`.`total_charge_value`) AS `charges`,`ret_purchase_return_other_charges`.`pur_ret_itm_id` AS `pur_ret_itm_id` from `ret_purchase_return_other_charges` group by `ret_purchase_return_other_charges`.`pur_ret_itm_id`) `retchr` on((`retchr`.`pur_ret_itm_id` = `pret`.`pur_ret_itm_id`))) left join (select sum(`ret_purchase_return_stone_items`.`ret_stone_amount`) AS `stamount`,`ret_purchase_return_stone_items`.`pur_ret_return_id` AS `pur_ret_return_id` from `ret_purchase_return_stone_items` group by `ret_purchase_return_stone_items`.`pur_ret_return_id`) `retst` on((`retst`.`pur_ret_return_id` = `pret`.`pur_ret_itm_id`))) left join `ret_purchase_order` `po` on((`po`.`po_id` = `pitm`.`po_item_po_id`))) left join `ret_grn_entry` `grn` on((`grn`.`grn_id` = `po`.`po_grn_id`))) left join `ret_karigar` `kr` on((`kr`.`id_karigar` = `ret`.`pur_ret_supplier_id`))) left join `ret_product_master` `pr` on((`pr`.`pro_id` = `pret`.`id_product`))) left join `ret_design_master` `pd` on((`pd`.`design_no` = `pret`.`id_design`))) left join `ret_category` `cat` on((`cat`.`id_ret_category` = `pr`.`cat_id`))) left join `metal` `met` on((`met`.`id_metal` = `cat`.`id_metal`)))
where ((`ret`.`pur_ret_convert_to` = 2) and (`grn`.`grn_type` = 4) and (`ret`.`bill_status` = 1))
group by `ret`.`pur_return_id`

-- UNION 8: Opening Balance (Amount)
union select 'OPENING' AS `category`,'' AS `product`,`pay`.`createdon` AS `trans_date`,`pay`.`id_smith_company_op_balance` AS `referenceno`,`pay`.`amount_type` AS `trans_type`,`pay`.`id_smith_company_op_balance` AS `trans_id`,0 AS `gross_wt`,0 AS `net_wt`,0 AS `no_of_pcs`,'' AS `purchase_touch`,0 AS `purewt`,`pay`.`id_karigar` AS `customer_id`,1 AS `trans_rec_type`,sum(`pay`.`amount`) AS `trans_amount`,'' AS `catid`,0 AS `stone_type`,'' AS `proid`,1 AS `trans_screen_id`,'' AS `id_metal`,'' AS `metal`,'' AS `rate`,'' AS `narration`,unix_timestamp(`pay`.`createdon`) AS `unixtransdate`,'' AS `dispuom` from `smith_company_op_balance` `pay`
where ((`pay`.`smith_type` = 2) and (`pay`.`stock_type` = 2) and (`pay`.`amount` > 0))
group by `pay`.`id_smith_company_op_balance`

-- UNION 9: Opening Balance (Weight)
union select 'OPENING' AS `category`,'' AS `product`,`pay`.`createdon` AS `trans_date`,`pay`.`id_smith_company_op_balance` AS `referenceno`,`pay`.`weight_type` AS `trans_type`,`pay`.`id_smith_company_op_balance` AS `trans_id`,ifnull(`pay`.`weight`,0) AS `gross_wt`,ifnull(`pay`.`weight`,0) AS `net_wt`,0 AS `no_of_pcs`,100 AS `purchase_touch`,ifnull(`pay`.`weight`,0) AS `purewt`,`pay`.`id_karigar` AS `customer_id`,1 AS `trans_rec_type`,0 AS `trans_amount`,'' AS `catid`,0 AS `stone_type`,'' AS `proid`,1 AS `trans_screen_id`,'' AS `id_metal`,'' AS `metal`,'' AS `rate`,'' AS `narration`,unix_timestamp(`pay`.`createdon`) AS `unixtransdate`,'' AS `dispuom` from `smith_company_op_balance` `pay`
where ((`pay`.`smith_type` = 2) and (`pay`.`stock_type` = 2) and (`pay`.`weight` > 0))
group by `pay`.`id_smith_company_op_balance`

-- UNION 10: Credit/Debit Notes
union select if((`pay`.`transtype` = 1),'Credit Note','Debit Note') AS `category`,'' AS `product`,`pay`.`transdate` AS `trans_date`,`pay`.`transbillno` AS `referenceno`,`pay`.`transtype` AS `trans_type`,`pay`.`transbillno` AS `trans_id`,0 AS `gross_wt`,0 AS `net_wt`,0 AS `no_of_pcs`,'' AS `purchase_touch`,0 AS `purewt`,`pay`.`supid` AS `customer_id`,1 AS `trans_rec_type`,sum(`pay`.`transamount`) AS `trans_amount`,'' AS `catid`,0 AS `stone_type`,'' AS `proid`,1 AS `trans_screen_id`,'' AS `id_metal`,'' AS `metal`,'' AS `rate`,`pay`.`naration` AS `narration`,unix_timestamp(`pay`.`transdate`) AS `unixtransdate`,'' AS `dispuom` from `ret_crdr_note` `pay`
where ((`pay`.`accountto` = 2) and (`pay`.`transamount` > 0) and (`pay`.`crdr_status` = 1))
group by `pay`.`crdrid`

-- UNION 11: Smith Opening Balance Metal Issue
union select `pd`.`design_name` AS `category`,`pr`.`product_name` AS `product`,`ki`.`met_issue_date` AS `trans_date`,`iss`.`ref_no` AS `referenceno`,2 AS `trans_type`,`iitm`.`issue_met_parent_id` AS `trans_id`,if((`cat`.`cat_type` = 2),0,if((ifnull(`uom`.`divided_by_value`,0) = 0),`iitm`.`issue_metal_wt`,round((`iitm`.`issue_metal_wt` / `uom`.`divided_by_value`),3))) AS `gross_wt`,if((`cat`.`cat_type` = 2),0,if((ifnull(`uom`.`divided_by_value`,0) = 0),`iitm`.`issue_metal_wt`,round((`iitm`.`issue_metal_wt` / `uom`.`divided_by_value`),3))) AS `net_wt`,ifnull(`iitm`.`issue_pcs`,1) AS `no_of_pcs`,'100' AS `purchase_touch`,if((`pr`.`stone_type` = 0),`iitm`.`issue_metal_pur_wt`,if((ifnull(`uom`.`divided_by_value`,0) = 0),`iitm`.`issue_metal_wt`,round((`iitm`.`issue_metal_wt` / `uom`.`divided_by_value`),3))) AS `purewt`,`iss`.`id_karigar` AS `customer_id`,1 AS `trans_rec_type`,0 AS `trans_amount`,`iitm`.`issue_cat_id` AS `catid`,`pr`.`stone_type` AS `stone_type`,`iitm`.`issu_met_pro_id` AS `proid`,2 AS `trans_screen_id`,`met`.`id_metal` AS `id_metal`,`met`.`metal` AS `metal`,'' AS `rate`,'' AS `narration`,unix_timestamp(`ki`.`met_issue_date`) AS `unixtransdate`,`uom`.`uom_short_code` AS `dispuom` from ((((((((`ret_karigar_metal_issue_details` `iitm` left join `ret_karigar_metal_issue` `ki` on((`ki`.`met_issue_id` = `iitm`.`issue_met_parent_id`))) left join `smith_company_op_balance` `iss` on((`iss`.`id_smith_company_op_balance` = `iitm`.`id_smith_company_op_balance`))) left join `ret_karigar` `kr` on((`kr`.`id_karigar` = `iss`.`id_karigar`))) left join `ret_category` `cat` on((`cat`.`id_ret_category` = `iitm`.`issue_cat_id`))) left join `metal` `met` on((`met`.`id_metal` = `cat`.`id_metal`))) left join `ret_product_master` `pr` on((`pr`.`pro_id` = `iitm`.`issu_met_pro_id`))) left join `ret_design_master` `pd` on((`pd`.`design_no` = `iitm`.`issu_met_id_design`))) left join `ret_uom` `uom` on((`uom`.`uom_id` = `iitm`.`issue_uom_id`)))
where ((`iitm`.`id_smith_company_op_balance` is not null) and (`ki`.`bill_status` = 1))
group by `iitm`.`issue_cat_id`,`iitm`.`issu_met_pro_id`,`iitm`.`issue_met_id`
order by `unixtransdate`;
