-- Migration Tool Backup
-- Entity: customer
-- Client: LOGIMAX
-- Date: 2026-03-20 17:59:59
-- Tables: customer, address

SET FOREIGN_KEY_CHECKS=0;

-- -----------------------------------------------
-- Table: customer
-- -----------------------------------------------
DROP TABLE IF EXISTS `customer`;
CREATE TABLE `customer` (
  `id_customer` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `reference_no` varchar(100) DEFAULT NULL COMMENT 'reference number with Offline s/w',
  `app_cus_code` varchar(45) DEFAULT NULL,
  `id_company` int(10) DEFAULT NULL COMMENT 'company wise customers',
  `id_branch` int(10) DEFAULT NULL COMMENT 'cus register branch',
  `id_village` int(10) DEFAULT NULL,
  `title` varchar(5) DEFAULT NULL,
  `initials` varchar(10) DEFAULT NULL,
  `lastname` varchar(32) DEFAULT NULL,
  `firstname` varchar(32) DEFAULT NULL,
  `date_of_birth` date DEFAULT NULL,
  `date_of_wed` date DEFAULT NULL,
  `spouse_name` varchar(35) DEFAULT NULL,
  `spouse_dob` date DEFAULT NULL,
  `gender` tinyint(1) DEFAULT NULL,
  `id_address` int(10) unsigned DEFAULT '0',
  `id_employee` int(10) unsigned DEFAULT '0',
  `email` varchar(128) DEFAULT NULL,
  `mobile` varchar(20) DEFAULT NULL,
  `phone` varchar(30) DEFAULT NULL,
  `nominee_name` varchar(50) DEFAULT NULL,
  `id_profession` int(10) DEFAULT NULL,
  `nominee_relationship` varchar(32) DEFAULT NULL,
  `nominee_mobile` varchar(20) DEFAULT NULL,
  `cus_img` varchar(50) DEFAULT NULL,
  `pan` varchar(15) DEFAULT NULL,
  `pan_proof` varchar(50) DEFAULT NULL,
  `ispan_req` tinyint(2) unsigned NOT NULL DEFAULT '0' COMMENT 'To disable editting pan no',
  `voterid` varchar(15) DEFAULT NULL,
  `voterid_proof` varchar(50) DEFAULT NULL,
  `rationcard` varchar(15) DEFAULT NULL,
  `rationcard_proof` varchar(50) DEFAULT NULL,
  `comments` varchar(200) DEFAULT NULL,
  `username` varchar(30) DEFAULT NULL,
  `passwd` varchar(32) DEFAULT NULL,
  `pwd_hash` varchar(300) DEFAULT NULL,
  `profile_complete` tinyint(1) DEFAULT '0',
  `active` tinyint(1) unsigned NOT NULL DEFAULT '1',
  `is_new` varchar(1) NOT NULL DEFAULT 'Y',
  `date_add` datetime DEFAULT CURRENT_TIMESTAMP,
  `custom_entry_date` date DEFAULT NULL,
  `date_upd` datetime DEFAULT NULL,
  `added_by` tinyint(2) unsigned NOT NULL DEFAULT '1' COMMENT '0 - WebApp , 1 - admin, 2 - MobileApp, 3 - Collection app, 4 - Retail App, 5- Sync, 6-Import 7-Retail admin',
  `notification` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `gst_number` varchar(50) DEFAULT NULL,
  `cus_ref_code` varchar(45) DEFAULT NULL COMMENT 'cus ref code(code will be stored for  referral type single)',
  `is_refbenefit_crt_cus` tinyint(4) unsigned NOT NULL DEFAULT '1' COMMENT '1-Benefit credited (used for referral type single)',
  `emp_ref_code` varchar(45) DEFAULT NULL COMMENT 'emp ref code(code will be stored for type single)',
  `is_refbenefit_crt_emp` tinyint(4) unsigned NOT NULL DEFAULT '1' COMMENT '1-Benefit credited (used for referral type single)',
  `religion` int(10) DEFAULT NULL COMMENT 'religion of custmer',
  `kyc_status` tinyint(1) NOT NULL DEFAULT '0' COMMENT '1 - KYC Completed',
  `is_cus_synced` tinyint(1) NOT NULL DEFAULT '0' COMMENT '0 - No, 1 - Yes',
  `last_sync_time` datetime DEFAULT NULL COMMENT 'Offline data Last synced date time',
  `last_payment_on` datetime DEFAULT NULL COMMENT 'Last payment date',
  `is_vip` tinyint(1) NOT NULL DEFAULT '0' COMMENT '1 - Yes, 0 - No',
  `cus_type` tinyint(1) NOT NULL DEFAULT '1' COMMENT '1-Individual ,2-Company',
  `send_promo_sms` int(11) NOT NULL DEFAULT '0',
  `aadharid` varchar(20) DEFAULT NULL,
  `driving_license_no` varchar(20) DEFAULT NULL,
  `passport_no` varchar(20) DEFAULT NULL,
  `nominee_address1` varchar(150) DEFAULT NULL,
  `nominee_address2` varchar(150) DEFAULT NULL,
  `id_agent` int(10) DEFAULT NULL,
  `pin_no` int(10) DEFAULT NULL,
  `refer_person` varchar(35) DEFAULT NULL,
  `refer_mobile` varchar(15) DEFAULT NULL,
  `aadhar_ImgName` varchar(250) DEFAULT NULL,
  `pan_ImgName` varchar(250) DEFAULT NULL,
  `dl_ImgName` varchar(250) DEFAULT NULL,
  `passport` varchar(100) DEFAULT NULL,
  `dl_number` varchar(100) DEFAULT NULL,
  `pp_ImgName` varchar(250) DEFAULT NULL,
  `fin_year_code` varchar(15) DEFAULT NULL,
  `opening_balance_amount` decimal(10,0) DEFAULT NULL,
  `nominee_pan` varchar(15) DEFAULT NULL,
  `vip_up_by` int(11) DEFAULT NULL,
  `vip_up_time` datetime DEFAULT NULL,
  `marital_status` int(2) NOT NULL DEFAULT '0' COMMENT '0 - Rather not to say, 1 - single, 2 - married',
  `languages_known` varchar(50) DEFAULT NULL COMMENT 'From languages master',
  `allocated_employee` varchar(100) DEFAULT NULL COMMENT 'For collection employee',
  `allocated_on` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_customer`),
  UNIQUE KEY `mobile` (`mobile`),
  UNIQUE KEY `CusIndex` (`id_customer`,`firstname`,`lastname`,`mobile`),
  UNIQUE KEY `id_company_3` (`id_company`,`id_branch`,`mobile`),
  UNIQUE KEY `gst_number` (`gst_number`,`mobile`) USING BTREE,
  UNIQUE KEY `pan` (`pan`,`mobile`) USING BTREE,
  UNIQUE KEY `aadharid` (`aadharid`,`mobile`) USING BTREE,
  KEY `id_company` (`id_company`),
  KEY `id_company_2` (`id_company`),
  KEY `id_village` (`id_village`),
  KEY `active` (`active`),
  KEY `cus_type` (`cus_type`),
  KEY `added_by` (`added_by`),
  KEY `mobile_2` (`mobile`),
  KEY `id_customer` (`id_customer`),
  KEY `passwd` (`passwd`),
  KEY `active_2` (`active`),
  KEY `email` (`email`),
  KEY `date_add` (`date_add`),
  KEY `firstname` (`firstname`),
  KEY `lastname` (`lastname`),
  KEY `username` (`username`),
  KEY `email_2` (`email`),
  KEY `added_by_2` (`added_by`),
  KEY `mobile_3` (`mobile`),
  KEY `id_customer_2` (`id_customer`),
  KEY `passwd_2` (`passwd`),
  KEY `active_3` (`active`),
  KEY `email_3` (`email`),
  KEY `date_add_2` (`date_add`),
  KEY `firstname_2` (`firstname`),
  KEY `lastname_2` (`lastname`),
  KEY `username_2` (`username`),
  KEY `email_4` (`email`),
  KEY `added_by_3` (`added_by`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- -----------------------------------------------
-- Table: address
-- -----------------------------------------------
DROP TABLE IF EXISTS `address`;
CREATE TABLE `address` (
  `id_address` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `id_country` int(10) unsigned DEFAULT NULL,
  `id_state` int(10) unsigned DEFAULT NULL,
  `id_city` int(10) unsigned DEFAULT NULL,
  `id_customer` int(10) unsigned NOT NULL DEFAULT '0',
  `id_employee` int(10) unsigned NOT NULL DEFAULT '0',
  `id_nominee` int(10) unsigned NOT NULL DEFAULT '0',
  `id_agent` int(10) unsigned DEFAULT NULL,
  `address1` varchar(100) DEFAULT NULL,
  `address2` varchar(100) DEFAULT NULL,
  `address3` varchar(100) DEFAULT NULL,
  `pincode` varchar(6) CHARACTER SET latin1 DEFAULT NULL,
  `date_add` datetime DEFAULT NULL,
  `date_upd` datetime DEFAULT NULL,
  `active` tinyint(1) unsigned NOT NULL DEFAULT '1',
  `deleted` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `company_name` varchar(100) DEFAULT NULL,
  `added_by` int(2) DEFAULT NULL COMMENT '0 - WebApp , 1 - admin, 2 - MobileApp, 3 - Collection app, 4 - Retail App, 5- Sync, 6-Import 7-Retail admin',
  PRIMARY KEY (`id_address`),
  UNIQUE KEY `AddIndex` (`id_address`,`id_customer`,`id_employee`),
  KEY `FK_address_employee` (`id_employee`),
  KEY `FK_address_customer` (`id_customer`),
  KEY `id_country` (`id_country`),
  KEY `id_state` (`id_state`),
  KEY `id_city` (`id_city`),
  KEY `id_agent` (`id_agent`),
  KEY `active` (`active`),
  KEY `id_customer` (`id_customer`),
  KEY `id_country_2` (`id_country`),
  KEY `id_state_2` (`id_state`),
  KEY `id_city_2` (`id_city`),
  KEY `id_customer_2` (`id_customer`),
  KEY `id_country_3` (`id_country`),
  KEY `id_state_3` (`id_state`),
  KEY `id_city_3` (`id_city`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

SET FOREIGN_KEY_CHECKS=1;
