-- Migration Tool Backup
-- Entity: customer
-- Client: LOGIMAX
-- Date: 2026-03-20 18:00:08
-- Tables: customer, address

SET FOREIGN_KEY_CHECKS=0;

-- -----------------------------------------------
-- Table: customer
-- -----------------------------------------------
DROP TABLE IF EXISTS `customer`;
CREATE TABLE `customer` (
  `id_customer` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `reference_no` varchar(100) DEFAULT NULL COMMENT 'reference number with Offline s/w',
  `app_cus_code` varchar(45) DEFAULT NULL,
  `id_company` int(10) DEFAULT NULL COMMENT 'company wise customers',
  `id_branch` int(10) DEFAULT NULL COMMENT 'cus register branch',
  `id_village` int(10) DEFAULT NULL,
  `title` varchar(5) DEFAULT NULL,
  `initials` varchar(10) DEFAULT NULL,
  `lastname` varchar(32) DEFAULT NULL,
  `firstname` varchar(32) DEFAULT NULL,
  `date_of_birth` date DEFAULT NULL,
  `date_of_wed` date DEFAULT NULL,
  `spouse_name` varchar(35) DEFAULT NULL,
  `spouse_dob` date DEFAULT NULL,
  `gender` tinyint(1) DEFAULT NULL,
  `id_address` int(10) unsigned DEFAULT '0',
  `id_employee` int(10) unsigned DEFAULT '0',
  `email` varchar(128) DEFAULT NULL,
  `mobile` varchar(20) DEFAULT NULL,
  `phone` varchar(30) DEFAULT NULL,
  `nominee_name` varchar(50) DEFAULT NULL,
  `id_profession` int(10) DEFAULT NULL,
  `nominee_relationship` varchar(32) DEFAULT NULL,
  `nominee_mobile` varchar(20) DEFAULT NULL,
  `cus_img` varchar(50) DEFAULT NULL,
  `pan` varchar(15) DEFAULT NULL,
  `pan_proof` varchar(50) DEFAULT NULL,
  `ispan_req` tinyint(2) unsigned NOT NULL DEFAULT '0' COMMENT 'To disable editting pan no',
  `voterid` varchar(15) DEFAULT NULL,
  `voterid_proof` varchar(50) DEFAULT NULL,
  `rationcard` varchar(15) DEFAULT NULL,
  `rationcard_proof` varchar(50) DEFAULT NULL,
  `comments` varchar(200) DEFAULT NULL,
  `username` varchar(30) DEFAULT NULL,
  `passwd` varchar(32) DEFAULT NULL,
  `pwd_hash` varchar(300) DEFAULT NULL,
  `profile_complete` tinyint(1) DEFAULT '0',
  `active` tinyint(1) unsigned NOT NULL DEFAULT '1',
  `is_new` varchar(1) NOT NULL DEFAULT 'Y',
  `date_add` datetime DEFAULT CURRENT_TIMESTAMP,
  `custom_entry_date` date DEFAULT NULL,
  `date_upd` datetime DEFAULT NULL,
  `added_by` tinyint(2) unsigned NOT NULL DEFAULT '1' COMMENT '0 - WebApp , 1 - admin, 2 - MobileApp, 3 - Collection app, 4 - Retail App, 5- Sync, 6-Import 7-Retail admin',
  `notification` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `gst_number` varchar(50) DEFAULT NULL,
  `cus_ref_code` varchar(45) DEFAULT NULL COMMENT 'cus ref code(code will be stored for  referral type single)',
  `is_refbenefit_crt_cus` tinyint(4) unsigned NOT NULL DEFAULT '1' COMMENT '1-Benefit credited (used for referral type single)',
  `emp_ref_code` varchar(45) DEFAULT NULL COMMENT 'emp ref code(code will be stored for type single)',
  `is_refbenefit_crt_emp` tinyint(4) unsigned NOT NULL DEFAULT '1' COMMENT '1-Benefit credited (used for referral type single)',
  `religion` int(10) DEFAULT NULL COMMENT 'religion of custmer',
  `kyc_status` tinyint(1) NOT NULL DEFAULT '0' COMMENT '1 - KYC Completed',
  `is_cus_synced` tinyint(1) NOT NULL DEFAULT '0' COMMENT '0 - No, 1 - Yes',
  `last_sync_time` datetime DEFAULT NULL COMMENT 'Offline data Last synced date time',
  `last_payment_on` datetime DEFAULT NULL COMMENT 'Last payment date',
  `is_vip` tinyint(1) NOT NULL DEFAULT '0' COMMENT '1 - Yes, 0 - No',
  `cus_type` tinyint(1) NOT NULL DEFAULT '1' COMMENT '1-Individual ,2-Company',
  `send_promo_sms` int(11) NOT NULL DEFAULT '0',
  `aadharid` varchar(20) DEFAULT NULL,
  `driving_license_no` varchar(20) DEFAULT NULL,
  `passport_no` varchar(20) DEFAULT NULL,
  `nominee_address1` varchar(150) DEFAULT NULL,
  `nominee_address2` varchar(150) DEFAULT NULL,
  `id_agent` int(10) DEFAULT NULL,
  `pin_no` int(10) DEFAULT NULL,
  `refer_person` varchar(35) DEFAULT NULL,
  `refer_mobile` varchar(15) DEFAULT NULL,
  `aadhar_ImgName` varchar(250) DEFAULT NULL,
  `pan_ImgName` varchar(250) DEFAULT NULL,
  `dl_ImgName` varchar(250) DEFAULT NULL,
  `passport` varchar(100) DEFAULT NULL,
  `dl_number` varchar(100) DEFAULT NULL,
  `pp_ImgName` varchar(250) DEFAULT NULL,
  `fin_year_code` varchar(15) DEFAULT NULL,
  `opening_balance_amount` decimal(10,0) DEFAULT NULL,
  `nominee_pan` varchar(15) DEFAULT NULL,
  `vip_up_by` int(11) DEFAULT NULL,
  `vip_up_time` datetime DEFAULT NULL,
  `marital_status` int(2) NOT NULL DEFAULT '0' COMMENT '0 - Rather not to say, 1 - single, 2 - married',
  `languages_known` varchar(50) DEFAULT NULL COMMENT 'From languages master',
  `allocated_employee` varchar(100) DEFAULT NULL COMMENT 'For collection employee',
  `allocated_on` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_customer`),
  UNIQUE KEY `mobile` (`mobile`),
  UNIQUE KEY `CusIndex` (`id_customer`,`firstname`,`lastname`,`mobile`),
  UNIQUE KEY `id_company_3` (`id_company`,`id_branch`,`mobile`),
  UNIQUE KEY `gst_number` (`gst_number`,`mobile`) USING BTREE,
  UNIQUE KEY `pan` (`pan`,`mobile`) USING BTREE,
  UNIQUE KEY `aadharid` (`aadharid`,`mobile`) USING BTREE,
  KEY `id_company` (`id_company`),
  KEY `id_company_2` (`id_company`),
  KEY `id_village` (`id_village`),
  KEY `active` (`active`),
  KEY `cus_type` (`cus_type`),
  KEY `added_by` (`added_by`),
  KEY `mobile_2` (`mobile`),
  KEY `id_customer` (`id_customer`),
  KEY `passwd` (`passwd`),
  KEY `active_2` (`active`),
  KEY `email` (`email`),
  KEY `date_add` (`date_add`),
  KEY `firstname` (`firstname`),
  KEY `lastname` (`lastname`),
  KEY `username` (`username`),
  KEY `email_2` (`email`),
  KEY `added_by_2` (`added_by`),
  KEY `mobile_3` (`mobile`),
  KEY `id_customer_2` (`id_customer`),
  KEY `passwd_2` (`passwd`),
  KEY `active_3` (`active`),
  KEY `email_3` (`email`),
  KEY `date_add_2` (`date_add`),
  KEY `firstname_2` (`firstname`),
  KEY `lastname_2` (`lastname`),
  KEY `username_2` (`username`),
  KEY `email_4` (`email`),
  KEY `added_by_3` (`added_by`)
) ENGINE=InnoDB AUTO_INCREMENT=60 DEFAULT CHARSET=utf8;

INSERT INTO `customer` (`id_customer`, `reference_no`, `app_cus_code`, `id_company`, `id_branch`, `id_village`, `title`, `initials`, `lastname`, `firstname`, `date_of_birth`, `date_of_wed`, `spouse_name`, `spouse_dob`, `gender`, `id_address`, `id_employee`, `email`, `mobile`, `phone`, `nominee_name`, `id_profession`, `nominee_relationship`, `nominee_mobile`, `cus_img`, `pan`, `pan_proof`, `ispan_req`, `voterid`, `voterid_proof`, `rationcard`, `rationcard_proof`, `comments`, `username`, `passwd`, `pwd_hash`, `profile_complete`, `active`, `is_new`, `date_add`, `custom_entry_date`, `date_upd`, `added_by`, `notification`, `gst_number`, `cus_ref_code`, `is_refbenefit_crt_cus`, `emp_ref_code`, `is_refbenefit_crt_emp`, `religion`, `kyc_status`, `is_cus_synced`, `last_sync_time`, `last_payment_on`, `is_vip`, `cus_type`, `send_promo_sms`, `aadharid`, `driving_license_no`, `passport_no`, `nominee_address1`, `nominee_address2`, `id_agent`, `pin_no`, `refer_person`, `refer_mobile`, `aadhar_ImgName`, `pan_ImgName`, `dl_ImgName`, `passport`, `dl_number`, `pp_ImgName`, `fin_year_code`, `opening_balance_amount`, `nominee_pan`, `vip_up_by`, `vip_up_time`, `marital_status`, `languages_known`, `allocated_employee`, `allocated_on`) VALUES
('1', NULL, NULL, NULL, '2', '1', NULL, NULL, '', 'KALAISELVI.S', NULL, NULL, NULL, NULL, NULL, '0', '0', NULL, '9999900114', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', '1', 'Y', '2026-03-20 00:00:00', NULL, NULL, '6', '0', NULL, NULL, '1', NULL, '1', NULL, '0', '0', NULL, NULL, '0', '1', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, '2026-03-20 18:00:03'),
('2', NULL, NULL, NULL, '2', '0', NULL, NULL, '', 'SEKAR.K', NULL, NULL, NULL, NULL, NULL, '0', '0', NULL, '9999900115', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', '1', 'Y', '2026-03-20 00:00:00', NULL, NULL, '6', '0', NULL, NULL, '1', NULL, '1', NULL, '0', '0', NULL, NULL, '0', '1', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, '2026-03-20 18:00:03'),
('3', NULL, NULL, NULL, '2', '0', NULL, NULL, '', 'SELVARAJ.P.S', NULL, NULL, NULL, NULL, NULL, '0', '0', NULL, '9999900003', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', '1', 'Y', '2026-03-20 00:00:00', NULL, NULL, '6', '0', NULL, NULL, '1', NULL, '1', NULL, '0', '0', NULL, NULL, '0', '1', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, '2026-03-20 18:00:03'),
('4', NULL, NULL, NULL, '2', '0', NULL, NULL, '', 'VANITHA RAJ.R.C', NULL, NULL, NULL, NULL, NULL, '0', '0', NULL, '9999900009', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', '1', 'Y', '2026-03-20 00:00:00', NULL, NULL, '6', '0', NULL, NULL, '1', NULL, '1', NULL, '0', '0', NULL, NULL, '0', '1', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, '2026-03-20 18:00:03'),
('5', NULL, NULL, NULL, '2', '0', NULL, NULL, '', 'SANMUGAPRIYA.R', NULL, NULL, NULL, NULL, NULL, '0', '0', NULL, '9999900010', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', '1', 'Y', '2026-03-20 00:00:00', NULL, NULL, '6', '0', NULL, NULL, '1', NULL, '1', NULL, '0', '0', NULL, NULL, '0', '1', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, '2026-03-20 18:00:03'),
('6', NULL, NULL, NULL, '2', '0', NULL, NULL, '', 'KARTHIGA.R', NULL, NULL, NULL, NULL, NULL, '0', '0', NULL, '9999900012', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', '1', 'Y', '2026-03-20 00:00:00', NULL, NULL, '6', '0', NULL, NULL, '1', NULL, '1', NULL, '0', '0', NULL, NULL, '0', '1', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, '2026-03-20 18:00:03'),
('7', NULL, NULL, NULL, '2', '0', NULL, NULL, '', 'AARTHI.S', NULL, NULL, NULL, NULL, NULL, '0', '0', NULL, '9999900015', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', '1', 'Y', '2026-03-20 00:00:00', NULL, NULL, '6', '0', NULL, NULL, '1', NULL, '1', NULL, '0', '0', NULL, NULL, '0', '1', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, '2026-03-20 18:00:03'),
('8', NULL, NULL, NULL, '2', '0', NULL, NULL, '', 'N.NNASUNTHARI', NULL, NULL, NULL, NULL, NULL, '0', '0', NULL, '9999900007', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', '1', 'Y', '2026-03-20 00:00:00', NULL, NULL, '6', '0', NULL, NULL, '1', NULL, '1', NULL, '0', '0', NULL, NULL, '0', '1', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, '2026-03-20 18:00:03'),
('9', NULL, NULL, NULL, '2', '0', NULL, NULL, '', 'VIJITHAVARSINI.P', NULL, NULL, NULL, NULL, NULL, '0', '0', NULL, '9999900023', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', '1', 'Y', '2026-03-20 00:00:00', NULL, NULL, '6', '0', NULL, NULL, '1', NULL, '1', NULL, '0', '0', NULL, NULL, '0', '1', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, '2026-03-20 18:00:03'),
('10', NULL, NULL, NULL, '2', '0', NULL, NULL, '', 'DIVYABHARATHI.B', NULL, NULL, NULL, NULL, NULL, '0', '0', NULL, '9999900024', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', '1', 'Y', '2026-03-20 00:00:00', NULL, NULL, '6', '0', NULL, NULL, '1', NULL, '1', NULL, '0', '0', NULL, NULL, '0', '1', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, '2026-03-20 18:00:03'),
('11', NULL, NULL, NULL, '2', '0', NULL, NULL, '', 'VISHNUPRASATH.B', NULL, NULL, NULL, NULL, NULL, '0', '0', NULL, '9999900025', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', '1', 'Y', '2026-03-20 00:00:00', NULL, NULL, '6', '0', NULL, NULL, '1', NULL, '1', NULL, '0', '0', NULL, NULL, '0', '1', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, '2026-03-20 18:00:03'),
('12', NULL, NULL, NULL, '2', '0', NULL, NULL, '', 'BABU NAVEENA S', NULL, NULL, NULL, NULL, NULL, '0', '0', NULL, '9364223295', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', '1', 'Y', '2026-03-20 00:00:00', NULL, NULL, '6', '0', NULL, NULL, '1', NULL, '1', NULL, '0', '0', NULL, NULL, '0', '1', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, '2026-03-20 18:00:03'),
('13', NULL, NULL, NULL, '2', '0', NULL, NULL, '', 'BANGAJAM.DR', NULL, NULL, NULL, NULL, NULL, '0', '0', NULL, '9999900017', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', '1', 'Y', '2026-03-20 00:00:00', NULL, NULL, '6', '0', NULL, NULL, '1', NULL, '1', NULL, '0', '0', NULL, NULL, '0', '1', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, '2026-03-20 18:00:03'),
('14', NULL, NULL, NULL, '2', '0', NULL, NULL, '', 'UMA.A', NULL, NULL, NULL, NULL, NULL, '0', '0', NULL, '9999900018', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', '1', 'Y', '2026-03-20 00:00:00', NULL, NULL, '6', '0', NULL, NULL, '1', NULL, '1', NULL, '0', '0', NULL, NULL, '0', '1', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, '2026-03-20 18:00:03'),
('15', NULL, NULL, NULL, '2', '0', NULL, NULL, '', 'M.KANCHANA', NULL, NULL, NULL, NULL, NULL, '0', '0', NULL, '6385001264', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', '1', 'Y', '2026-03-20 00:00:00', NULL, NULL, '6', '0', NULL, NULL, '1', NULL, '1', NULL, '0', '0', NULL, NULL, '0', '1', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, '2026-03-20 18:00:03'),
('16', NULL, NULL, NULL, '2', '0', NULL, NULL, '', 'SELVA MARY.R', NULL, NULL, NULL, NULL, NULL, '0', '0', NULL, '9159981147', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', '1', 'Y', '2026-03-20 00:00:00', NULL, NULL, '6', '0', NULL, NULL, '1', NULL, '1', NULL, '0', '0', NULL, NULL, '0', '1', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, '2026-03-20 18:00:03'),
('17', NULL, NULL, NULL, '2', '0', NULL, NULL, '', 'MAHESHWARI K', NULL, NULL, NULL, NULL, NULL, '0', '0', NULL, '6374544887', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', '1', 'Y', '2026-03-20 00:00:00', NULL, NULL, '6', '0', NULL, NULL, '1', NULL, '1', NULL, '0', '0', NULL, NULL, '0', '1', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, '2026-03-20 18:00:03'),
('18', NULL, NULL, NULL, '2', '0', NULL, NULL, '', 'FAKKER MOHAMED A', NULL, NULL, NULL, NULL, NULL, '0', '0', NULL, '9787473635', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', '1', 'Y', '2026-03-20 00:00:00', NULL, NULL, '6', '0', NULL, NULL, '1', NULL, '1', NULL, '0', '0', NULL, NULL, '0', '1', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, '2026-03-20 18:00:03'),
('19', NULL, NULL, NULL, '2', '0', NULL, NULL, '', 'PREMA P', NULL, NULL, NULL, NULL, NULL, '0', '0', NULL, '7806952700', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', '1', 'Y', '2026-03-20 00:00:00', NULL, NULL, '6', '0', NULL, NULL, '1', NULL, '1', NULL, '0', '0', NULL, NULL, '0', '1', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, '2026-03-20 18:00:03'),
('20', NULL, NULL, NULL, '2', '0', NULL, NULL, '', 'MOHITH B', NULL, NULL, NULL, NULL, NULL, '0', '0', NULL, '8667428871', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', '1', 'Y', '2026-03-20 00:00:00', NULL, NULL, '6', '0', NULL, NULL, '1', NULL, '1', NULL, '0', '0', NULL, NULL, '0', '1', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, '2026-03-20 18:00:03'),
('21', NULL, NULL, NULL, '2', '0', NULL, NULL, '', 'ERAN BEE', NULL, NULL, NULL, NULL, NULL, '0', '0', NULL, '9500684258', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', '1', 'Y', '2026-03-20 00:00:00', NULL, NULL, '6', '0', NULL, NULL, '1', NULL, '1', NULL, '0', '0', NULL, NULL, '0', '1', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, '2026-03-20 18:00:03'),
('22', NULL, NULL, NULL, '2', '0', NULL, NULL, '', 'SHARMILA BEGAM', NULL, NULL, NULL, NULL, NULL, '0', '0', NULL, '9999900021', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', '1', 'Y', '2026-03-20 00:00:00', NULL, NULL, '6', '0', NULL, NULL, '1', NULL, '1', NULL, '0', '0', NULL, NULL, '0', '1', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, '2026-03-20 18:00:03'),
('23', NULL, NULL, NULL, '2', '0', NULL, NULL, '', 'DINESH KUMAR.M', NULL, NULL, NULL, NULL, NULL, '0', '0', NULL, '9999900057', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', '1', 'Y', '2026-03-20 00:00:00', NULL, NULL, '6', '0', NULL, NULL, '1', NULL, '1', NULL, '0', '0', NULL, NULL, '0', '1', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, '2026-03-20 18:00:03'),
('24', NULL, NULL, NULL, '2', '0', NULL, NULL, '', 'RAJESWARI.V', NULL, NULL, NULL, NULL, NULL, '0', '0', NULL, '9999900063', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', '1', 'Y', '2026-03-20 00:00:00', NULL, NULL, '6', '0', NULL, NULL, '1', NULL, '1', NULL, '0', '0', NULL, NULL, '0', '1', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, '2026-03-20 18:00:03'),
('25', NULL, NULL, NULL, '2', '0', NULL, NULL, '', 'SARAVANAN.K', NULL, NULL, NULL, NULL, NULL, '0', '0', NULL, '9999900072', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', '1', 'Y', '2026-03-20 00:00:00', NULL, NULL, '6', '0', NULL, NULL, '1', NULL, '1', NULL, '0', '0', NULL, NULL, '0', '1', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, '2026-03-20 18:00:03'),
('26', NULL, NULL, NULL, '2', '0', NULL, NULL, '', 'NETHAJI', NULL, NULL, NULL, NULL, NULL, '0', '0', NULL, '9999900073', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', '1', 'Y', '2026-03-20 00:00:00', NULL, NULL, '6', '0', NULL, NULL, '1', NULL, '1', NULL, '0', '0', NULL, NULL, '0', '1', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, '2026-03-20 18:00:03'),
('27', NULL, NULL, NULL, '2', '0', NULL, NULL, '', 'PRABU.S', NULL, NULL, NULL, NULL, NULL, '0', '0', NULL, '9999900074', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', '1', 'Y', '2026-03-20 00:00:00', NULL, NULL, '6', '0', NULL, NULL, '1', NULL, '1', NULL, '0', '0', NULL, NULL, '0', '1', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, '2026-03-20 18:00:03'),
('28', NULL, NULL, NULL, '2', '0', NULL, NULL, '', 'MAGENTHRAVARMAN', NULL, NULL, NULL, NULL, NULL, '0', '0', NULL, '9999900011', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', '1', 'Y', '2026-03-20 00:00:00', NULL, NULL, '6', '0', NULL, NULL, '1', NULL, '1', NULL, '0', '0', NULL, NULL, '0', '1', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, '2026-03-20 18:00:03'),
('29', NULL, NULL, NULL, '2', '0', NULL, NULL, '', 'INDHRA ELANTHENDTRAL', NULL, NULL, NULL, NULL, NULL, '0', '0', NULL, '9999900075', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', '1', 'Y', '2026-03-20 00:00:00', NULL, NULL, '6', '0', NULL, NULL, '1', NULL, '1', NULL, '0', '0', NULL, NULL, '0', '1', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, '2026-03-20 18:00:03'),
('30', NULL, NULL, NULL, '2', '0', NULL, NULL, '', 'BASEER AHAMAD', NULL, NULL, NULL, NULL, NULL, '0', '0', NULL, '9999900079', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', '1', 'Y', '2026-03-20 00:00:00', NULL, NULL, '6', '0', NULL, NULL, '1', NULL, '1', NULL, '0', '0', NULL, NULL, '0', '1', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, '2026-03-20 18:00:03'),
('31', NULL, NULL, NULL, '2', '0', NULL, NULL, '', 'REJINA R', NULL, NULL, NULL, NULL, NULL, '0', '0', NULL, '8015321184', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', '1', 'Y', '2026-03-20 00:00:00', NULL, NULL, '6', '0', NULL, NULL, '1', NULL, '1', NULL, '0', '0', NULL, NULL, '0', '1', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, '2026-03-20 18:00:03'),
('32', NULL, NULL, NULL, '2', '0', NULL, NULL, '', 'AMARAVATHI.M', NULL, NULL, NULL, NULL, NULL, '0', '0', NULL, '9999900031', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', '1', 'Y', '2026-03-20 00:00:00', NULL, NULL, '6', '0', NULL, NULL, '1', NULL, '1', NULL, '0', '0', NULL, NULL, '0', '1', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, '2026-03-20 18:00:03'),
('33', NULL, NULL, NULL, '2', '0', NULL, NULL, '', 'GOVINDHA RAJAN .C', NULL, NULL, NULL, NULL, NULL, '0', '0', NULL, '8610041720', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', '1', 'Y', '2026-03-20 00:00:00', NULL, NULL, '6', '0', NULL, NULL, '1', NULL, '1', NULL, '0', '0', NULL, NULL, '0', '1', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, '2026-03-20 18:00:03'),
('34', NULL, NULL, NULL, '2', '0', NULL, NULL, '', 'CHANDHRA.S', NULL, NULL, NULL, NULL, NULL, '0', '0', NULL, '9999900033', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', '1', 'Y', '2026-03-20 00:00:00', NULL, NULL, '6', '0', NULL, NULL, '1', NULL, '1', NULL, '0', '0', NULL, NULL, '0', '1', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, '2026-03-20 18:00:03'),
('35', NULL, NULL, NULL, '2', '0', NULL, NULL, '', 'GEETHA RANI.S', NULL, NULL, NULL, NULL, NULL, '0', '0', NULL, '9999900034', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', '1', 'Y', '2026-03-20 00:00:00', NULL, NULL, '6', '0', NULL, NULL, '1', NULL, '1', NULL, '0', '0', NULL, NULL, '0', '1', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, '2026-03-20 18:00:03'),
('36', NULL, NULL, NULL, '2', '0', NULL, NULL, '', 'SARVESH', NULL, NULL, NULL, NULL, NULL, '0', '0', NULL, '9999900086', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', '1', 'Y', '2026-03-20 00:00:00', NULL, NULL, '6', '0', NULL, NULL, '1', NULL, '1', NULL, '0', '0', NULL, NULL, '0', '1', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, '2026-03-20 18:00:03'),
('37', NULL, NULL, NULL, '2', '0', NULL, NULL, '', 'VIJAYALAKSHMI', NULL, NULL, NULL, NULL, NULL, '0', '0', NULL, '9999900089', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', '1', 'Y', '2026-03-20 00:00:00', NULL, NULL, '6', '0', NULL, NULL, '1', NULL, '1', NULL, '0', '0', NULL, NULL, '0', '1', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, '2026-03-20 18:00:03'),
('38', NULL, NULL, NULL, '2', '0', NULL, NULL, '', 'RAMAKRISHNAN C', NULL, NULL, NULL, NULL, NULL, '0', '0', NULL, '9976229213', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', '1', 'Y', '2026-03-20 00:00:00', NULL, NULL, '6', '0', NULL, NULL, '1', NULL, '1', NULL, '0', '0', NULL, NULL, '0', '1', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, '2026-03-20 18:00:03'),
('39', NULL, NULL, NULL, '2', '0', NULL, NULL, '', 'JEMANAVAMERRY.P', NULL, NULL, NULL, NULL, NULL, '0', '0', NULL, '9999900043', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', '1', 'Y', '2026-03-20 00:00:00', NULL, NULL, '6', '0', NULL, NULL, '1', NULL, '1', NULL, '0', '0', NULL, NULL, '0', '1', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, '2026-03-20 18:00:03'),
('40', NULL, NULL, NULL, '2', '0', NULL, NULL, '', 'JAARJ.A', NULL, NULL, NULL, NULL, NULL, '0', '0', NULL, '9999900098', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', '1', 'Y', '2026-03-20 00:00:00', NULL, NULL, '6', '0', NULL, NULL, '1', NULL, '1', NULL, '0', '0', NULL, NULL, '0', '1', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, '2026-03-20 18:00:03'),
('41', NULL, NULL, NULL, '2', '0', NULL, NULL, '', 'VIGNESH KUMAR.D', NULL, NULL, NULL, NULL, NULL, '0', '0', NULL, '9999900013', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', '1', 'Y', '2026-03-20 00:00:00', NULL, NULL, '6', '0', NULL, NULL, '1', NULL, '1', NULL, '0', '0', NULL, NULL, '0', '1', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, '2026-03-20 18:00:03'),
('42', NULL, NULL, NULL, '2', '0', NULL, NULL, '', 'DEEPIKA SREE.D', NULL, NULL, NULL, NULL, NULL, '0', '0', NULL, '9999900014', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', '1', 'Y', '2026-03-20 00:00:00', NULL, NULL, '6', '0', NULL, NULL, '1', NULL, '1', NULL, '0', '0', NULL, NULL, '0', '1', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, '2026-03-20 18:00:03'),
('43', NULL, NULL, NULL, '2', '0', NULL, NULL, '', 'RAJA', NULL, NULL, NULL, NULL, NULL, '0', '0', NULL, '9842832616', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', '1', 'Y', '2026-03-20 00:00:00', NULL, NULL, '6', '0', NULL, NULL, '1', NULL, '1', NULL, '0', '0', NULL, NULL, '0', '1', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, '2026-03-20 18:00:03'),
('44', NULL, NULL, NULL, '2', '0', NULL, NULL, '', 'SARASWATHI', NULL, NULL, NULL, NULL, NULL, '0', '0', NULL, '9999900055', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', '1', 'Y', '2026-03-20 00:00:00', NULL, NULL, '6', '0', NULL, NULL, '1', NULL, '1', NULL, '0', '0', NULL, NULL, '0', '1', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, '2026-03-20 18:00:03'),
('45', NULL, NULL, NULL, '2', '0', NULL, NULL, '', 'RACHEL', NULL, NULL, NULL, NULL, NULL, '0', '0', NULL, '9999900020', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', '1', 'Y', '2026-03-20 00:00:00', NULL, NULL, '6', '0', NULL, NULL, '1', NULL, '1', NULL, '0', '0', NULL, NULL, '0', '1', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, '2026-03-20 18:00:03'),
('46', NULL, NULL, NULL, '2', '0', NULL, NULL, '', 'VINOTHINI.S', NULL, NULL, NULL, NULL, NULL, '0', '0', NULL, '9999900056', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', '1', 'Y', '2026-03-20 00:00:00', NULL, NULL, '6', '0', NULL, NULL, '1', NULL, '1', NULL, '0', '0', NULL, NULL, '0', '1', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, '2026-03-20 18:00:03'),
('47', NULL, NULL, NULL, '2', '0', NULL, NULL, '', 'KASTHOORI.V', NULL, NULL, NULL, NULL, NULL, '0', '0', NULL, '9999900019', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', '1', 'Y', '2026-03-20 00:00:00', NULL, NULL, '6', '0', NULL, NULL, '1', NULL, '1', NULL, '0', '0', NULL, NULL, '0', '1', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, '2026-03-20 18:00:03'),
('48', NULL, NULL, NULL, '2', '0', NULL, NULL, '', 'KESAVAN.M', NULL, NULL, NULL, NULL, NULL, '0', '0', NULL, '9999900058', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', '1', 'Y', '2026-03-20 00:00:00', NULL, NULL, '6', '0', NULL, NULL, '1', NULL, '1', NULL, '0', '0', NULL, NULL, '0', '1', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, '2026-03-20 18:00:03'),
('49', NULL, NULL, NULL, '2', '0', NULL, NULL, '', 'ASARUTHIN.A', NULL, NULL, NULL, NULL, NULL, '0', '0', NULL, '9999900059', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', '1', 'Y', '2026-03-20 00:00:00', NULL, NULL, '6', '0', NULL, NULL, '1', NULL, '1', NULL, '0', '0', NULL, NULL, '0', '1', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, '2026-03-20 18:00:03'),
('50', NULL, NULL, NULL, '2', '0', NULL, NULL, '', 'MALARKODI.V', NULL, NULL, NULL, NULL, NULL, '0', '0', NULL, '9999900060', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', '1', 'Y', '2026-03-20 00:00:00', NULL, NULL, '6', '0', NULL, NULL, '1', NULL, '1', NULL, '0', '0', NULL, NULL, '0', '1', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, '2026-03-20 18:00:03'),
('51', NULL, NULL, NULL, '2', '0', NULL, NULL, '', 'DINESH KUMAR.M', NULL, NULL, NULL, NULL, NULL, '0', '0', NULL, '9999900062', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', '1', 'Y', '2026-03-20 00:00:00', NULL, NULL, '6', '0', NULL, NULL, '1', NULL, '1', NULL, '0', '0', NULL, NULL, '0', '1', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, '2026-03-20 18:00:03'),
('52', NULL, NULL, NULL, '2', '0', NULL, NULL, '', 'RAJESWARI', NULL, NULL, NULL, NULL, NULL, '0', '0', NULL, '9999900113', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', '1', 'Y', '2026-03-20 00:00:00', NULL, NULL, '6', '0', NULL, NULL, '1', NULL, '1', NULL, '0', '0', NULL, NULL, '0', '1', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, '2026-03-20 18:00:03'),
('53', NULL, NULL, NULL, '2', '0', NULL, NULL, '', 'NIVETHA.T', NULL, NULL, NULL, NULL, NULL, '0', '0', NULL, '9999900022', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', '1', 'Y', '2026-03-20 00:00:00', NULL, NULL, '6', '0', NULL, NULL, '1', NULL, '1', NULL, '0', '0', NULL, NULL, '0', '1', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, '2026-03-20 18:00:03'),
('54', NULL, NULL, NULL, '2', '0', NULL, NULL, '', 'MALLIGA.R', NULL, NULL, NULL, NULL, NULL, '0', '0', NULL, '9999900064', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', '1', 'Y', '2026-03-20 00:00:00', NULL, NULL, '6', '0', NULL, NULL, '1', NULL, '1', NULL, '0', '0', NULL, NULL, '0', '1', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, '2026-03-20 18:00:03'),
('55', NULL, NULL, NULL, '2', '0', NULL, NULL, '', 'KALAIARASI', NULL, NULL, NULL, NULL, NULL, '0', '0', NULL, '9999900065', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', '1', 'Y', '2026-03-20 00:00:00', NULL, NULL, '6', '0', NULL, NULL, '1', NULL, '1', NULL, '0', '0', NULL, NULL, '0', '1', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, '2026-03-20 18:00:03'),
('56', NULL, NULL, NULL, '2', '0', NULL, NULL, '', 'SUDHA.T', NULL, NULL, NULL, NULL, NULL, '0', '0', NULL, '9999900066', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', '1', 'Y', '2026-03-20 00:00:00', NULL, NULL, '6', '0', NULL, NULL, '1', NULL, '1', NULL, '0', '0', NULL, NULL, '0', '1', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, '2026-03-20 18:00:03'),
('57', NULL, NULL, NULL, '2', '0', NULL, NULL, '', 'DURGA', NULL, NULL, NULL, NULL, NULL, '0', '0', NULL, '9999900116', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', '1', 'Y', '2026-03-20 00:00:00', NULL, NULL, '6', '0', NULL, NULL, '1', NULL, '1', NULL, '0', '0', NULL, NULL, '0', '1', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, '2026-03-20 18:00:03'),
('58', NULL, NULL, NULL, '2', '0', NULL, NULL, '', 'IYAAVU', NULL, NULL, NULL, NULL, NULL, '0', '0', NULL, '9999900118', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', '1', 'Y', '2026-03-20 00:00:00', NULL, NULL, '6', '0', NULL, NULL, '1', NULL, '1', NULL, '0', '0', NULL, NULL, '0', '1', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, '2026-03-20 18:00:03'),
('59', NULL, NULL, NULL, '2', '0', NULL, NULL, '', 'SEETHA', NULL, NULL, NULL, NULL, NULL, '0', '0', NULL, '9999900120', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', '1', 'Y', '2026-03-20 00:00:00', NULL, NULL, '6', '0', NULL, NULL, '1', NULL, '1', NULL, '0', '0', NULL, NULL, '0', '1', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, '2026-03-20 18:00:03');

-- -----------------------------------------------
-- Table: address
-- -----------------------------------------------
DROP TABLE IF EXISTS `address`;
CREATE TABLE `address` (
  `id_address` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `id_country` int(10) unsigned DEFAULT NULL,
  `id_state` int(10) unsigned DEFAULT NULL,
  `id_city` int(10) unsigned DEFAULT NULL,
  `id_customer` int(10) unsigned NOT NULL DEFAULT '0',
  `id_employee` int(10) unsigned NOT NULL DEFAULT '0',
  `id_nominee` int(10) unsigned NOT NULL DEFAULT '0',
  `id_agent` int(10) unsigned DEFAULT NULL,
  `address1` varchar(100) DEFAULT NULL,
  `address2` varchar(100) DEFAULT NULL,
  `address3` varchar(100) DEFAULT NULL,
  `pincode` varchar(6) CHARACTER SET latin1 DEFAULT NULL,
  `date_add` datetime DEFAULT NULL,
  `date_upd` datetime DEFAULT NULL,
  `active` tinyint(1) unsigned NOT NULL DEFAULT '1',
  `deleted` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `company_name` varchar(100) DEFAULT NULL,
  `added_by` int(2) DEFAULT NULL COMMENT '0 - WebApp , 1 - admin, 2 - MobileApp, 3 - Collection app, 4 - Retail App, 5- Sync, 6-Import 7-Retail admin',
  PRIMARY KEY (`id_address`),
  UNIQUE KEY `AddIndex` (`id_address`,`id_customer`,`id_employee`),
  KEY `FK_address_employee` (`id_employee`),
  KEY `FK_address_customer` (`id_customer`),
  KEY `id_country` (`id_country`),
  KEY `id_state` (`id_state`),
  KEY `id_city` (`id_city`),
  KEY `id_agent` (`id_agent`),
  KEY `active` (`active`),
  KEY `id_customer` (`id_customer`),
  KEY `id_country_2` (`id_country`),
  KEY `id_state_2` (`id_state`),
  KEY `id_city_2` (`id_city`),
  KEY `id_customer_2` (`id_customer`),
  KEY `id_country_3` (`id_country`),
  KEY `id_state_3` (`id_state`),
  KEY `id_city_3` (`id_city`)
) ENGINE=InnoDB AUTO_INCREMENT=60 DEFAULT CHARSET=utf8;

INSERT INTO `address` (`id_address`, `id_country`, `id_state`, `id_city`, `id_customer`, `id_employee`, `id_nominee`, `id_agent`, `address1`, `address2`, `address3`, `pincode`, `date_add`, `date_upd`, `active`, `deleted`, `company_name`, `added_by`) VALUES
('1', NULL, NULL, NULL, '1', '0', '0', NULL, 'MADHA KOVIL STREET', '', '', '', NULL, NULL, '1', '0', NULL, '6'),
('2', NULL, NULL, NULL, '2', '0', '0', NULL, 'MUGAMATHIYAR STREET', '', '', '', NULL, NULL, '1', '0', NULL, '6'),
('3', NULL, NULL, NULL, '3', '0', '0', NULL, 'D/O ANANDAN', '', '', '', NULL, NULL, '1', '0', NULL, '6'),
('4', NULL, NULL, NULL, '4', '0', '0', NULL, 'W/O BASKAR', '', '', '', NULL, NULL, '1', '0', NULL, '6'),
('5', NULL, NULL, NULL, '5', '0', '0', NULL, 'S/O, NALLAPPAN', '', '', '', NULL, NULL, '1', '0', NULL, '6'),
('6', NULL, NULL, NULL, '6', '0', '0', NULL, 'KALLAKURICHI', '', '', '', NULL, NULL, '1', '0', NULL, '6'),
('7', NULL, NULL, NULL, '7', '0', '0', NULL, 'VILANTHANGAL ROAD', '', '', '', NULL, NULL, '1', '0', NULL, '6'),
('8', NULL, NULL, NULL, '8', '0', '0', NULL, '27,AZHAGAR NAGAR KALLAKURICHI', '', '', '', NULL, NULL, '1', '0', NULL, '6'),
('9', NULL, NULL, NULL, '9', '0', '0', NULL, 'PILLAIYAR KOVIL STREET', '', '', '', NULL, NULL, '1', '0', NULL, '6'),
('10', NULL, NULL, NULL, '10', '0', '0', NULL, 'W/O AANANTH', '', '', '', NULL, NULL, '1', '0', NULL, '6'),
('11', NULL, NULL, NULL, '11', '0', '0', NULL, 'KAVARAI ST', '', '', '', NULL, NULL, '1', '0', NULL, '6'),
('12', NULL, NULL, NULL, '12', '0', '0', NULL, '1 93 Aruntbathiyer st V. Alambalam EMAPPER', 'EMAPPER', 'KALLAKURICHI', '', NULL, NULL, '1', '0', NULL, '6'),
('13', NULL, NULL, NULL, '13', '0', '0', NULL, 'KALLAI MAIN ROAD', '', '', '', NULL, NULL, '1', '0', NULL, '6'),
('14', NULL, NULL, NULL, '14', '0', '0', NULL, '4/93 THENKEERANUR', '', '', '', NULL, NULL, '1', '0', NULL, '6'),
('15', NULL, NULL, NULL, '15', '0', '0', NULL, '28B/4B RAJA NAGAR', '', '', '', NULL, NULL, '1', '0', NULL, '6'),
('16', NULL, NULL, NULL, '16', '0', '0', NULL, 'MIDDLE STREET PRITHIVEEMANGALAM', '', '', '', NULL, NULL, '1', '0', NULL, '6'),
('17', NULL, NULL, NULL, '17', '0', '0', NULL, 'WEST STREET PORASAKURICHI', 'PORASAKURICHI', 'KALLAKURICHI', '', NULL, NULL, '1', '0', NULL, '6'),
('18', NULL, NULL, NULL, '18', '0', '0', NULL, 'PANDARA STREET KOOTHAKUDI', 'KOOTHAKUDI', 'KALLAKURICHI', '', NULL, NULL, '1', '0', NULL, '6'),
('19', NULL, NULL, NULL, '19', '0', '0', NULL, 'W/O THIRUNAUKARASU MELUR', 'MELUR', 'KALLAKURICHI', '', NULL, NULL, '1', '0', NULL, '6'),
('20', NULL, NULL, NULL, '20', '0', '0', NULL, 'MARIYAMMAN KOVIL ST MELUR', 'MELUR', 'KALLAKURICHI', '', NULL, NULL, '1', '0', NULL, '6'),
('21', NULL, NULL, NULL, '21', '0', '0', NULL, 'S/OTHIRUMAL', '', '', '', NULL, NULL, '1', '0', NULL, '6'),
('22', NULL, NULL, NULL, '22', '0', '0', NULL, 'SOUTH STREET THIYAGADURUGAM', 'THIYAGADURUGAM', 'kallakurichi', '', NULL, NULL, '1', '0', NULL, '6'),
('23', NULL, NULL, NULL, '23', '0', '0', NULL, '185 WEST STREET', '', '', '', NULL, NULL, '1', '0', NULL, '6'),
('24', NULL, NULL, NULL, '24', '0', '0', NULL, 'DURUGAM ROAD', '', '', '', NULL, NULL, '1', '0', NULL, '6'),
('25', NULL, NULL, NULL, '25', '0', '0', NULL, '175 EAST STREET MATHUR', '', '', '', NULL, NULL, '1', '0', NULL, '6'),
('26', NULL, NULL, NULL, '26', '0', '0', NULL, 'S/O KANNAN', '', '', '', NULL, NULL, '1', '0', NULL, '6'),
('27', NULL, NULL, NULL, '27', '0', '0', NULL, 'KALLAKURICHI', '', '', '', NULL, NULL, '1', '0', NULL, '6'),
('28', NULL, NULL, NULL, '28', '0', '0', NULL, 'ALATHUR', '', '', '', NULL, NULL, '1', '0', NULL, '6'),
('29', NULL, NULL, NULL, '29', '0', '0', NULL, 'MIDDLE STREET', '', '', '', NULL, NULL, '1', '0', NULL, '6'),
('30', NULL, NULL, NULL, '30', '0', '0', NULL, 'JINNA NAGAR THIYGADURUGAM', '', '', '', NULL, NULL, '1', '0', NULL, '6'),
('31', NULL, NULL, NULL, '31', '0', '0', NULL, 'WEST STREET THIYAGADURUGAM', 'THIYAGADURUGAM', 'KALLAKURICHI', '', NULL, NULL, '1', '0', NULL, '6'),
('32', NULL, NULL, NULL, '32', '0', '0', NULL, 'MAIN ROAD', '', '', '', NULL, NULL, '1', '0', NULL, '6'),
('33', NULL, NULL, NULL, '33', '0', '0', NULL, 'THENKEERANUR', 'THENKEERANUR', 'kallakurichi', '', NULL, NULL, '1', '0', NULL, '6'),
('34', NULL, NULL, NULL, '34', '0', '0', NULL, 'PERUMAL PILLAI ST', '', '', '', NULL, NULL, '1', '0', NULL, '6'),
('35', NULL, NULL, NULL, '35', '0', '0', NULL, 'KALLAKURICHI', '', '', '', NULL, NULL, '1', '0', NULL, '6'),
('36', NULL, NULL, NULL, '36', '0', '0', NULL, 'MEENAVAR STREET', '', '', '', NULL, NULL, '1', '0', NULL, '6'),
('37', NULL, NULL, NULL, '37', '0', '0', NULL, 'KALLAKURICHI', '', '', '', NULL, NULL, '1', '0', NULL, '6'),
('38', NULL, NULL, NULL, '38', '0', '0', NULL, '1/32 NORTH STREET SEMBARAM PATTU', 'SEMBARAM PATTU', 'kallakurichi', '', NULL, NULL, '1', '0', NULL, '6'),
('39', NULL, NULL, NULL, '39', '0', '0', NULL, '525 SOUTH STREET', '', '', '', NULL, NULL, '1', '0', NULL, '6'),
('40', NULL, NULL, NULL, '40', '0', '0', NULL, 'VILANTHANGAL ROAD', '', '', '', NULL, NULL, '1', '0', NULL, '6'),
('41', NULL, NULL, NULL, '41', '0', '0', NULL, 'NO5/14 NALLATHAMPI UDYAR ST', '', '', '', NULL, NULL, '1', '0', NULL, '6'),
('42', NULL, NULL, NULL, '42', '0', '0', NULL, 'KALLAKURICHI', '', '', '', NULL, NULL, '1', '0', NULL, '6'),
('43', NULL, NULL, NULL, '43', '0', '0', NULL, 'D/O RAMACHANDIRAN SANGARAPURAM', 'SANGARAPURAM', 'kallakurichi', '', NULL, NULL, '1', '0', NULL, '6'),
('44', NULL, NULL, NULL, '44', '0', '0', NULL, 'MAIN ROAD', '', '', '', NULL, NULL, '1', '0', NULL, '6'),
('45', NULL, NULL, NULL, '45', '0', '0', NULL, 'KUDIYANA STREET', '', '', '', NULL, NULL, '1', '0', NULL, '6'),
('46', NULL, NULL, NULL, '46', '0', '0', NULL, '10/39,KATTU KOTTAI', '', '', '', NULL, NULL, '1', '0', NULL, '6'),
('47', NULL, NULL, NULL, '47', '0', '0', NULL, 'NEW HOUSE', '', '', '', NULL, NULL, '1', '0', NULL, '6'),
('48', NULL, NULL, NULL, '48', '0', '0', NULL, '136D, V.O.C NAGAR', '', '', '', NULL, NULL, '1', '0', NULL, '6'),
('49', NULL, NULL, NULL, '49', '0', '0', NULL, 'KALLAKURICHI', '', '', '', NULL, NULL, '1', '0', NULL, '6'),
('50', NULL, NULL, NULL, '50', '0', '0', NULL, '2/2 EAST STREET', '', '', '', NULL, NULL, '1', '0', NULL, '6'),
('51', NULL, NULL, NULL, '51', '0', '0', NULL, 'SELVA NAGAR 2ND CROSS STREET', '', '', '', NULL, NULL, '1', '0', NULL, '6'),
('52', NULL, NULL, NULL, '52', '0', '0', NULL, '41 EAST STREET', '', '', '', NULL, NULL, '1', '0', NULL, '6'),
('53', NULL, NULL, NULL, '53', '0', '0', NULL, '12C/5A RAMANAR ST', '', '', '', NULL, NULL, '1', '0', NULL, '6'),
('54', NULL, NULL, NULL, '54', '0', '0', NULL, 'MADURAI VEERAN KOVIL STREET', '', '', '', NULL, NULL, '1', '0', NULL, '6'),
('55', NULL, NULL, NULL, '55', '0', '0', NULL, 'KALLAKURICHI', '', '', '', NULL, NULL, '1', '0', NULL, '6'),
('56', NULL, NULL, NULL, '56', '0', '0', NULL, '282/5 POOTTAI ROAD', '', '', '', NULL, NULL, '1', '0', NULL, '6'),
('57', NULL, NULL, NULL, '57', '0', '0', NULL, 'KALLAKURICHI', '', '', '', NULL, NULL, '1', '0', NULL, '6'),
('58', NULL, NULL, NULL, '58', '0', '0', NULL, 'THITAKUDI', '', '', '', NULL, NULL, '1', '0', NULL, '6'),
('59', NULL, NULL, NULL, '59', '0', '0', NULL, 'WEST STREET', '', '', '', NULL, NULL, '1', '0', NULL, '6');

SET FOREIGN_KEY_CHECKS=1;
