<?php
defined('BASEPATH') OR exit('No direct script access allowed');

/**
 * Bill Variables Definition — bill.php
 * ============================================================
 * This file declares every variable that is available when the
 * "Bill" data source is selected in the Print Designer.
 *
 * These variables are populated by billing_invoice() controller
 * via get_receipt_data() → map_billing_data_to_template() in
 * admin/application/helpers/receipt_helper.php
 *
 * Usage in designer: {{variable_name}}
 * ============================================================
 */

function get_bill_variables()
{
    return [

        // ── Company / Shop Details ──────────────────────────────
        [
            'column'      => 'company_name',
            'tag'         => '{{company_name}}',
            'type'        => 'text',
            'group'       => 'Company',
            'description' => 'Shop / Company name',
            'is_pk'       => false,
        ],
        [
            'column'      => 'company_address',
            'tag'         => '{{company_address}}',
            'type'        => 'text',
            'group'       => 'Company',
            'description' => 'Full company address',
            'is_pk'       => false,
        ],
        [
            'column'      => 'company_mobile',
            'tag'         => '{{company_mobile}}',
            'type'        => 'text',
            'group'       => 'Company',
            'description' => 'Company mobile number',
            'is_pk'       => false,
        ],
        [
            'column'      => 'company_email',
            'tag'         => '{{company_email}}',
            'type'        => 'text',
            'group'       => 'Company',
            'description' => 'Company email address',
            'is_pk'       => false,
        ],
        [
            'column'      => 'company_gstin',
            'tag'         => '{{company_gstin}}',
            'type'        => 'text',
            'group'       => 'Company',
            'description' => 'Company GST number',
            'is_pk'       => false,
        ],
        [
            'column'      => 'company_pan',
            'tag'         => '{{company_pan}}',
            'type'        => 'text',
            'group'       => 'Company',
            'description' => 'Company PAN number',
            'is_pk'       => false,
        ],
        [
            'column'      => 'company_state',
            'tag'         => '{{company_state}}',
            'type'        => 'text',
            'group'       => 'Company',
            'description' => 'Company state name',
            'is_pk'       => false,
        ],
        [
            'column'      => 'company_state_code',
            'tag'         => '{{company_state_code}}',
            'type'        => 'text',
            'group'       => 'Company',
            'description' => 'Company state GST code',
            'is_pk'       => false,
        ],

        // ── Bill / Invoice Details ──────────────────────────────
        [
            'column'      => 'invoice_no',
            'tag'         => '{{invoice_no}}',
            'type'        => 'text',
            'group'       => 'Bill',
            'description' => 'Invoice / Reference number (e.g. BRH-SA-0001)',
            'is_pk'       => false,
        ],
        [
            'column'      => 'bill_date',
            'tag'         => '{{bill_date}}',
            'type'        => 'date',
            'group'       => 'Bill',
            'description' => 'Bill date (dd-mm-yyyy)',
            'is_pk'       => false,
        ],
        [
            'column'      => 'bill_time',
            'tag'         => '{{bill_time}}',
            'type'        => 'text',
            'group'       => 'Bill',
            'description' => 'Bill time (hh:mm AM/PM)',
            'is_pk'       => false,
        ],
        [
            'column'      => 'title',
            'tag'         => '{{title}}',
            'type'        => 'text',
            'group'       => 'Bill',
            'description' => 'Bill type label (e.g. Sales Bill, Credit Collection)',
            'is_pk'       => false,
        ],
        [
            'column'      => 'irnno',
            'tag'         => '{{irnno}}',
            'type'        => 'text',
            'group'       => 'Bill',
            'description' => 'E-Invoice IRN number',
            'is_pk'       => false,
        ],
        [
            'column'      => 'ack_no',
            'tag'         => '{{ack_no}}',
            'type'        => 'text',
            'group'       => 'Bill',
            'description' => 'E-Invoice acknowledgement number',
            'is_pk'       => false,
        ],
        [
            'column'      => 'remark',
            'tag'         => '{{remark}}',
            'type'        => 'text',
            'group'       => 'Bill',
            'description' => 'Bill remarks / notes',
            'is_pk'       => false,
        ],
        [
            'column'      => 'terms_condition',
            'tag'         => '{{terms_condition}}',
            'type'        => 'text',
            'group'       => 'Bill',
            'description' => 'Terms and conditions text',
            'is_pk'       => false,
        ],

        // ── Customer Details ────────────────────────────────────
        [
            'column'      => 'customer_name',
            'tag'         => '{{customer_name}}',
            'type'        => 'text',
            'group'       => 'Customer',
            'description' => 'Customer full name',
            'is_pk'       => false,
        ],
        [
            'column'      => 'customer_mobile',
            'tag'         => '{{customer_mobile}}',
            'type'        => 'text',
            'group'       => 'Customer',
            'description' => 'Customer mobile number',
            'is_pk'       => false,
        ],
        [
            'column'      => 'customer_address',
            'tag'         => '{{customer_address}}',
            'type'        => 'text',
            'group'       => 'Customer',
            'description' => 'Customer address (line 1 + line 2)',
            'is_pk'       => false,
        ],
        [
            'column'      => 'customer_city',
            'tag'         => '{{customer_city}}',
            'type'        => 'text',
            'group'       => 'Customer',
            'description' => 'Customer city',
            'is_pk'       => false,
        ],
        [
            'column'      => 'customer_pincode',
            'tag'         => '{{customer_pincode}}',
            'type'        => 'text',
            'group'       => 'Customer',
            'description' => 'Customer PIN code',
            'is_pk'       => false,
        ],
        [
            'column'      => 'customer_state',
            'tag'         => '{{customer_state}}',
            'type'        => 'text',
            'group'       => 'Customer',
            'description' => 'Customer state name',
            'is_pk'       => false,
        ],
        [
            'column'      => 'customer_gstin',
            'tag'         => '{{customer_gstin}}',
            'type'        => 'text',
            'group'       => 'Customer',
            'description' => 'Customer GST number',
            'is_pk'       => false,
        ],
        [
            'column'      => 'customer_pan',
            'tag'         => '{{customer_pan}}',
            'type'        => 'text',
            'group'       => 'Customer',
            'description' => 'Customer PAN number',
            'is_pk'       => false,
        ],
        [
            'column'      => 'customer_adhar',
            'tag'         => '{{customer_adhar}}',
            'type'        => 'text',
            'group'       => 'Customer',
            'description' => 'Customer Aadhaar number',
            'is_pk'       => false,
        ],
        [
            'column'      => 'customer_passport',
            'tag'         => '{{customer_passport}}',
            'type'        => 'text',
            'group'       => 'Customer',
            'description' => 'Customer passport number',
            'is_pk'       => false,
        ],

        // ── Metal Rates ─────────────────────────────────────────
        [
            'column'      => 'gold_rate',
            'tag'         => '{{gold_rate}}',
            'type'        => 'number',
            'group'       => 'Metal Rates',
            'description' => 'Gold rate 22KT per gram',
            'is_pk'       => false,
        ],
        [
            'column'      => 'gold_rate_18ct',
            'tag'         => '{{gold_rate_18ct}}',
            'type'        => 'number',
            'group'       => 'Metal Rates',
            'description' => 'Gold rate 18KT per gram',
            'is_pk'       => false,
        ],
        [
            'column'      => 'gold_rate_24ct',
            'tag'         => '{{gold_rate_24ct}}',
            'type'        => 'number',
            'group'       => 'Metal Rates',
            'description' => 'Gold rate 24KT per gram',
            'is_pk'       => false,
        ],
        [
            'column'      => 'silver_rate',
            'tag'         => '{{silver_rate}}',
            'type'        => 'number',
            'group'       => 'Metal Rates',
            'description' => 'Silver rate per gram',
            'is_pk'       => false,
        ],

        // ── Sales Items (loop) ───────────────────────────────────
        [
            'column'      => '#items ... /items',
            'tag'         => '{{#items}}',
            'type'        => 'loop',
            'group'       => 'Sales Items',
            'description' => 'Loop start — iterate sales item rows',
            'is_pk'       => false,
        ],
        [
            'column'      => 'items.sno',
            'tag'         => '{{sno}}',
            'type'        => 'text',
            'group'       => 'Sales Items',
            'description' => 'Serial number (inside loop)',
            'is_pk'       => false,
        ],
        [
            'column'      => 'items.description',
            'tag'         => '{{description}}',
            'type'        => 'text',
            'group'       => 'Sales Items',
            'description' => 'Item description / design name',
            'is_pk'       => false,
        ],
        [
            'column'      => 'items.hsn_code',
            'tag'         => '{{hsn_code}}',
            'type'        => 'text',
            'group'       => 'Sales Items',
            'description' => 'HSN / SAC code',
            'is_pk'       => false,
        ],
        [
            'column'      => 'items.purity',
            'tag'         => '{{purity}}',
            'type'        => 'text',
            'group'       => 'Sales Items',
            'description' => 'Purity hallmark (e.g. 916, 925)',
            'is_pk'       => false,
        ],
        [
            'column'      => 'items.qty',
            'tag'         => '{{qty}}',
            'type'        => 'number',
            'group'       => 'Sales Items',
            'description' => 'Quantity / piece count',
            'is_pk'       => false,
        ],
        [
            'column'      => 'items.gross_wt',
            'tag'         => '{{gross_wt}}',
            'type'        => 'number',
            'group'       => 'Sales Items',
            'description' => 'Gross weight in grams',
            'is_pk'       => false,
        ],
        [
            'column'      => 'items.net_wt',
            'tag'         => '{{net_wt}}',
            'type'        => 'number',
            'group'       => 'Sales Items',
            'description' => 'Net weight (after stone deduction)',
            'is_pk'       => false,
        ],
        [
            'column'      => 'items.wastage_percent',
            'tag'         => '{{wastage_percent}}',
            'type'        => 'number',
            'group'       => 'Sales Items',
            'description' => 'Wastage / VA percentage',
            'is_pk'       => false,
        ],
        [
            'column'      => 'items.wastage_wt',
            'tag'         => '{{wastage_wt}}',
            'type'        => 'number',
            'group'       => 'Sales Items',
            'description' => 'Wastage weight in grams',
            'is_pk'       => false,
        ],
        [
            'column'      => 'items.va_content',
            'tag'         => '{{va_content}}',
            'type'        => 'text',
            'group'       => 'Sales Items',
            'description' => 'Value addition content / purity stamp',
            'is_pk'       => false,
        ],
        [
            'column'      => 'items.mc',
            'tag'         => '{{mc}}',
            'type'        => 'number',
            'group'       => 'Sales Items',
            'description' => 'Making charge amount',
            'is_pk'       => false,
        ],
        [
            'column'      => 'items.rate',
            'tag'         => '{{rate}}',
            'type'        => 'number',
            'group'       => 'Sales Items',
            'description' => 'Metal rate per gram',
            'is_pk'       => false,
        ],
        [
            'column'      => 'items.amount',
            'tag'         => '{{amount}}',
            'type'        => 'number',
            'group'       => 'Sales Items',
            'description' => 'Item total amount',
            'is_pk'       => false,
        ],
        [
            'column'      => 'items.taxable_amount',
            'tag'         => '{{taxable_amount}}',
            'type'        => 'number',
            'group'       => 'Sales Items',
            'description' => 'Taxable amount (ex-GST)',
            'is_pk'       => false,
        ],
        [
            'column'      => 'items.stone_less',
            'tag'         => '{{stone_less}}',
            'type'        => 'number',
            'group'       => 'Sales Items',
            'description' => 'Stone deduction amount',
            'is_pk'       => false,
        ],
        [
            'column'      => 'items.metal_less',
            'tag'         => '{{metal_less}}',
            'type'        => 'number',
            'group'       => 'Sales Items',
            'description' => 'Metal deduction amount',
            'is_pk'       => false,
        ],
        [
            'column'      => 'items.tag_no',
            'tag'         => '{{tag_no}}',
            'type'        => 'text',
            'group'       => 'Sales Items',
            'description' => 'Tag / barcode number',
            'is_pk'       => false,
        ],
        [
            'column'      => 'items.huid',
            'tag'         => '{{huid}}',
            'type'        => 'text',
            'group'       => 'Sales Items',
            'description' => 'HUID (Hallmarking Unique ID)',
            'is_pk'       => false,
        ],
        [
            'column'      => 'items.order_no',
            'tag'         => '{{order_no}}',
            'type'        => 'text',
            'group'       => 'Sales Items',
            'description' => 'Order number linked to this item',
            'is_pk'       => false,
        ],
        // Sales totals (scalars outside loop)
        [
            'column'      => 'total_sales_qty',
            'tag'         => '{{total_sales_qty}}',
            'type'        => 'number',
            'group'       => 'Sales Items',
            'description' => 'Total pieces sold',
            'is_pk'       => false,
        ],
        [
            'column'      => 'total_sales_gross_wt',
            'tag'         => '{{total_sales_gross_wt}}',
            'type'        => 'number',
            'group'       => 'Sales Items',
            'description' => 'Total sales gross weight',
            'is_pk'       => false,
        ],
        [
            'column'      => 'total_sales_net_wt',
            'tag'         => '{{total_sales_net_wt}}',
            'type'        => 'number',
            'group'       => 'Sales Items',
            'description' => 'Total sales net weight',
            'is_pk'       => false,
        ],

        // ── Totals & Amounts ────────────────────────────────────

        [
            'column'      => 'total_qty',
            'tag'         => '{{total_qty}}',
            'type'        => 'number',
            'group'       => 'Totals',
            'description' => 'Total number of pieces',
            'is_pk'       => false,
        ],
        [
            'column'      => 'total_gross_wt',
            'tag'         => '{{total_gross_wt}}',
            'type'        => 'number',
            'group'       => 'Totals',
            'description' => 'Total gross weight (grams)',
            'is_pk'       => false,
        ],
        [
            'column'      => 'total_net_wt',
            'tag'         => '{{total_net_wt}}',
            'type'        => 'number',
            'group'       => 'Totals',
            'description' => 'Total net weight (grams)',
            'is_pk'       => false,
        ],
        [
            'column'      => 'sub_total',
            'tag'         => '{{sub_total}}',
            'type'        => 'number',
            'group'       => 'Totals',
            'description' => 'Sub total (before tax)',
            'is_pk'       => false,
        ],
        [
            'column'      => 'cgst_amount',
            'tag'         => '{{cgst_amount}}',
            'type'        => 'number',
            'group'       => 'Totals',
            'description' => 'Total CGST amount',
            'is_pk'       => false,
        ],
        [
            'column'      => 'sgst_amount',
            'tag'         => '{{sgst_amount}}',
            'type'        => 'number',
            'group'       => 'Totals',
            'description' => 'Total SGST amount',
            'is_pk'       => false,
        ],
        [
            'column'      => 'igst_amount',
            'tag'         => '{{igst_amount}}',
            'type'        => 'number',
            'group'       => 'Totals',
            'description' => 'Total IGST amount',
            'is_pk'       => false,
        ],
        [
            'column'      => 'round_off',
            'tag'         => '{{round_off}}',
            'type'        => 'number',
            'group'       => 'Totals',
            'description' => 'Rounding adjustment amount',
            'is_pk'       => false,
        ],
        [
            'column'      => 'handling_charges',
            'tag'         => '{{handling_charges}}',
            'type'        => 'number',
            'group'       => 'Totals',
            'description' => 'Handling / service charges',
            'is_pk'       => false,
        ],
        [
            'column'      => 'grand_total',
            'tag'         => '{{grand_total}}',
            'type'        => 'number',
            'group'       => 'Totals',
            'description' => 'Final bill total amount',
            'is_pk'       => false,
        ],
        [
            'column'      => 'amount_in_words',
            'tag'         => '{{amount_in_words}}',
            'type'        => 'text',
            'group'       => 'Totals',
            'description' => 'Grand total spelled in words',
            'is_pk'       => false,
        ],
        [
            'column'      => 'total_paid',
            'tag'         => '{{total_paid}}',
            'type'        => 'number',
            'group'       => 'Totals',
            'description' => 'Amount already paid/received',
            'is_pk'       => false,
        ],
        [
            'column'      => 'balance_amount',
            'tag'         => '{{balance_amount}}',
            'type'        => 'number',
            'group'       => 'Totals',
            'description' => 'Balance / due amount (grand_total - total_paid)',
            'is_pk'       => false,
        ],
        [
            'column'      => 'order_amount',
            'tag'         => '{{order_amount}}',
            'type'        => 'number',
            'group'       => 'Totals',
            'description' => 'Order advance total amount',
            'is_pk'       => false,
        ],

        // ── Payment Modes ───────────────────────────────────────
        [
            'column'      => 'pay_cash',
            'tag'         => '{{pay_cash}}',
            'type'        => 'number',
            'group'       => 'Payment',
            'description' => 'Amount paid by cash',
            'is_pk'       => false,
        ],
        [
            'column'      => 'pay_cheque',
            'tag'         => '{{pay_cheque}}',
            'type'        => 'number',
            'group'       => 'Payment',
            'description' => 'Amount paid by cheque',
            'is_pk'       => false,
        ],
        [
            'column'      => 'pay_card',
            'tag'         => '{{pay_card}}',
            'type'        => 'number',
            'group'       => 'Payment',
            'description' => 'Amount paid by debit/credit card',
            'is_pk'       => false,
        ],
        [
            'column'      => 'pay_upi',
            'tag'         => '{{pay_upi}}',
            'type'        => 'number',
            'group'       => 'Payment',
            'description' => 'Amount paid via UPI',
            'is_pk'       => false,
        ],
        [
            'column'      => 'pay_neft',
            'tag'         => '{{pay_neft}}',
            'type'        => 'number',
            'group'       => 'Payment',
            'description' => 'Amount paid via NEFT',
            'is_pk'       => false,
        ],
        [
            'column'      => 'pay_rtgs',
            'tag'         => '{{pay_rtgs}}',
            'type'        => 'number',
            'group'       => 'Payment',
            'description' => 'Amount paid via RTGS',
            'is_pk'       => false,
        ],
        [
            'column'      => 'pay_imps',
            'tag'         => '{{pay_imps}}',
            'type'        => 'number',
            'group'       => 'Payment',
            'description' => 'Amount paid via IMPS',
            'is_pk'       => false,
        ],

        // ── Employee / Staff ─────────────────────────────────────
        [
            'column'      => 'billed_by',
            'tag'         => '{{billed_by}}',
            'type'        => 'text',
            'group'       => 'Employee',
            'description' => 'Name of employee who billed',
            'is_pk'       => false,
        ],
        [
            'column'      => 'sales_emp',
            'tag'         => '{{sales_emp}}',
            'type'        => 'text',
            'group'       => 'Employee',
            'description' => 'Name of salesperson from estimation',
            'is_pk'       => false,
        ],

        // ── Bill Type Flags ─────────────────────────────────────
        [
            'column'      => 'is_sales_only',
            'tag'         => '{{is_sales_only}}',
            'type'        => 'boolean',
            'group'       => 'Flags',
            'description' => 'True if this is a pure sales bill (bill_type = 1)',
            'is_pk'       => false,
        ],
        [
            'column'      => 'is_sales_and_purchase',
            'tag'         => '{{is_sales_and_purchase}}',
            'type'        => 'boolean',
            'group'       => 'Flags',
            'description' => 'True if this is a combined sales + purchase bill',
            'is_pk'       => false,
        ],
        [
            'column'      => 'is_purchase_only',
            'tag'         => '{{is_purchase_only}}',
            'type'        => 'boolean',
            'group'       => 'Flags',
            'description' => 'True if this is a purchase-only bill',
            'is_pk'       => false,
        ],
        [
            'column'      => 'is_sales_return',
            'tag'         => '{{is_sales_return}}',
            'type'        => 'boolean',
            'group'       => 'Flags',
            'description' => 'True if this is a sales return bill',
            'is_pk'       => false,
        ],
        [
            'column'      => 'is_credit_collection',
            'tag'         => '{{is_credit_collection}}',
            'type'        => 'boolean',
            'group'       => 'Flags',
            'description' => 'True if this is a credit collection bill',
            'is_pk'       => false,
        ],
        [
            'column'      => 'is_order_receipt',
            'tag'         => '{{is_order_receipt}}',
            'type'        => 'boolean',
            'group'       => 'Flags',
            'description' => 'True if this is an order advance receipt',
            'is_pk'       => false,
        ],
        [
            'column'      => 'is_order_delivery',
            'tag'         => '{{is_order_delivery}}',
            'type'        => 'boolean',
            'group'       => 'Flags',
            'description' => 'True if this is an order delivery bill',
            'is_pk'       => false,
        ],
        [
            'column'      => 'is_chit_preclose',
            'tag'         => '{{is_chit_preclose}}',
            'type'        => 'boolean',
            'group'       => 'Flags',
            'description' => 'True if this is a chit pre-close bill',
            'is_pk'       => false,
        ],
        // ── Adjustments ─────────────────────────────────────────
        [
            'column'      => 'chit_adj',
            'tag'         => '{{chit_adj}}',
            'type'        => 'number',
            'group'       => 'Adjustments',
            'description' => 'Chit scheme adjustment amount',
            'is_pk'       => false,
        ],
        [
            'column'      => 'advance_adj',
            'tag'         => '{{advance_adj}}',
            'type'        => 'number',
            'group'       => 'Adjustments',
            'description' => 'Advance receipt adjustment amount',
            'is_pk'       => false,
        ],
        [
            'column'      => 'order_advance_adj',
            'tag'         => '{{order_advance_adj}}',
            'type'        => 'number',
            'group'       => 'Adjustments',
            'description' => 'Order advance adjustment amount',
            'is_pk'       => false,
        ],
        [
            'column'      => 'receipt_adj',
            'tag'         => '{{receipt_adj}}',
            'type'        => 'number',
            'group'       => 'Adjustments',
            'description' => 'Generic receipt adjustment',
            'is_pk'       => false,
        ],

        // ── Bill Reference Numbers ───────────────────────────────
        [
            'column'      => 'sales_ref_no',
            'tag'         => '{{sales_ref_no}}',
            'type'        => 'text',
            'group'       => 'Reference Numbers',
            'description' => 'Sales reference number (e.g. SA-2024-001)',
            'is_pk'       => false,
        ],
        [
            'column'      => 'pur_ref_no',
            'tag'         => '{{pur_ref_no}}',
            'type'        => 'text',
            'group'       => 'Reference Numbers',
            'description' => 'Purchase reference number (e.g. PU-2024-001)',
            'is_pk'       => false,
        ],
        [
            'column'      => 'counter_name',
            'tag'         => '{{counter_name}}',
            'type'        => 'text',
            'group'       => 'Reference Numbers',
            'description' => 'Billing counter name',
            'is_pk'       => false,
        ],
        [
            'column'      => 'fin_year',
            'tag'         => '{{fin_year}}',
            'type'        => 'text',
            'group'       => 'Reference Numbers',
            'description' => 'Financial year (e.g. 2024-25)',
            'is_pk'       => false,
        ],

        // ── Bill Summary Totals ──────────────────────────────────
        [
            'column'      => 'total_items',
            'tag'         => '{{total_items}}',
            'type'        => 'number',
            'group'       => 'Bill Summary',
            'description' => 'Total number of item lines',
            'is_pk'       => false,
        ],
        [
            'column'      => 'total_pieces',
            'tag'         => '{{total_pieces}}',
            'type'        => 'number',
            'group'       => 'Bill Summary',
            'description' => 'Total piece count across all items',
            'is_pk'       => false,
        ],
        [
            'column'      => 'total_mc_amount',
            'tag'         => '{{total_mc_amount}}',
            'type'        => 'number',
            'group'       => 'Bill Summary',
            'description' => 'Total making charge amount',
            'is_pk'       => false,
        ],
        [
            'column'      => 'total_taxable',
            'tag'         => '{{total_taxable}}',
            'type'        => 'number',
            'group'       => 'Bill Summary',
            'description' => 'Total taxable amount (before GST)',
            'is_pk'       => false,
        ],
        [
            'column'      => 'discount_amount',
            'tag'         => '{{discount_amount}}',
            'type'        => 'number',
            'group'       => 'Bill Summary',
            'description' => 'Total discount applied',
            'is_pk'       => false,
        ],
        [
            'column'      => 'tcs_amount',
            'tag'         => '{{tcs_amount}}',
            'type'        => 'number',
            'group'       => 'Bill Summary',
            'description' => 'TCS amount',
            'is_pk'       => false,
        ],
        [
            'column'      => 'tds_amount',
            'tag'         => '{{tds_amount}}',
            'type'        => 'number',
            'group'       => 'Bill Summary',
            'description' => 'TDS amount',
            'is_pk'       => false,
        ],
        [
            'column'      => 'net_total',
            'tag'         => '{{net_total}}',
            'type'        => 'number',
            'group'       => 'Bill Summary',
            'description' => 'Net payable total',
            'is_pk'       => false,
        ],

        // ── Old / Purchase Metal — Totals ────────────────────────
        [
            'column'      => 'old_metal_total_qty',
            'tag'         => '{{old_metal_total_qty}}',
            'type'        => 'number',
            'group'       => 'Old/Purchase Metal',
            'description' => 'Total pieces of old metal tendered',
            'is_pk'       => false,
        ],
        [
            'column'      => 'total_old_gross_wt',
            'tag'         => '{{total_old_gross_wt}}',
            'type'        => 'number',
            'group'       => 'Old/Purchase Metal',
            'description' => 'Total old metal gross weight (g)',
            'is_pk'       => false,
        ],
        [
            'column'      => 'total_old_net_wt',
            'tag'         => '{{total_old_net_wt}}',
            'type'        => 'number',
            'group'       => 'Old/Purchase Metal',
            'description' => 'Total old metal net weight (g)',
            'is_pk'       => false,
        ],
        [
            'column'      => 'total_old_amount',
            'tag'         => '{{total_old_amount}}',
            'type'        => 'number',
            'group'       => 'Old/Purchase Metal',
            'description' => 'Total old metal value / purchase amount',
            'is_pk'       => false,
        ],
        // Loop tag markers (not renderable scalars, but shown as guidance)
        [
            'column'      => '#purchase_items ... /purchase_items',
            'tag'         => '{{#purchase_items}}',
            'type'        => 'loop',
            'group'       => 'Old/Purchase Metal',
            'description' => 'Loop start — iterate purchase/old-metal rows',
            'is_pk'       => false,
        ],
        [
            'column'      => 'purchase_items.sno',
            'tag'         => '{{purchase_item.sno}}',
            'type'        => 'text',
            'group'       => 'Old/Purchase Metal',
            'description' => 'S.No (inside purchase loop)',
            'is_pk'       => false,
        ],
        [
            'column'      => 'purchase_items.metal_name',
            'tag'         => '{{purchase_item.metal_name}}',
            'type'        => 'text',
            'group'       => 'Old/Purchase Metal',
            'description' => 'Metal name (Gold / Silver)',
            'is_pk'       => false,
        ],
        [
            'column'      => 'purchase_items.old_metal_type',
            'tag'         => '{{purchase_item.old_metal_type}}',
            'type'        => 'text',
            'group'       => 'Old/Purchase Metal',
            'description' => 'Old metal type label',
            'is_pk'       => false,
        ],
        [
            'column'      => 'purchase_items.piece',
            'tag'         => '{{purchase_item.piece}}',
            'type'        => 'number',
            'group'       => 'Old/Purchase Metal',
            'description' => 'Number of pieces',
            'is_pk'       => false,
        ],
        [
            'column'      => 'purchase_items.gross_wt',
            'tag'         => '{{purchase_item.gross_wt}}',
            'type'        => 'number',
            'group'       => 'Old/Purchase Metal',
            'description' => 'Gross weight (g)',
            'is_pk'       => false,
        ],
        [
            'column'      => 'purchase_items.stone_wt',
            'tag'         => '{{purchase_item.stone_wt}}',
            'type'        => 'number',
            'group'       => 'Old/Purchase Metal',
            'description' => 'Stone deduction weight',
            'is_pk'       => false,
        ],
        [
            'column'      => 'purchase_items.dust_wt',
            'tag'         => '{{purchase_item.dust_wt}}',
            'type'        => 'number',
            'group'       => 'Old/Purchase Metal',
            'description' => 'Dust deduction weight',
            'is_pk'       => false,
        ],
        [
            'column'      => 'purchase_items.net_wt',
            'tag'         => '{{purchase_item.net_wt}}',
            'type'        => 'number',
            'group'       => 'Old/Purchase Metal',
            'description' => 'Net weight after deductions',
            'is_pk'       => false,
        ],
        [
            'column'      => 'purchase_items.purity',
            'tag'         => '{{purchase_item.purity}}',
            'type'        => 'text',
            'group'       => 'Old/Purchase Metal',
            'description' => 'Purity hallmark (e.g. 916)',
            'is_pk'       => false,
        ],
        [
            'column'      => 'purchase_items.touch',
            'tag'         => '{{purchase_item.touch}}',
            'type'        => 'number',
            'group'       => 'Old/Purchase Metal',
            'description' => 'Touch percentage',
            'is_pk'       => false,
        ],
        [
            'column'      => 'purchase_items.wastage_percent',
            'tag'         => '{{purchase_item.wastage_percent}}',
            'type'        => 'number',
            'group'       => 'Old/Purchase Metal',
            'description' => 'Wastage percentage',
            'is_pk'       => false,
        ],
        [
            'column'      => 'purchase_items.wast_wt',
            'tag'         => '{{purchase_item.wast_wt}}',
            'type'        => 'number',
            'group'       => 'Old/Purchase Metal',
            'description' => 'Wastage weight',
            'is_pk'       => false,
        ],
        [
            'column'      => 'purchase_items.rate_per_gram',
            'tag'         => '{{purchase_item.rate_per_gram}}',
            'type'        => 'number',
            'group'       => 'Old/Purchase Metal',
            'description' => 'Purchase rate per gram',
            'is_pk'       => false,
        ],
        [
            'column'      => 'purchase_items.amount',
            'tag'         => '{{purchase_item.amount}}',
            'type'        => 'number',
            'group'       => 'Old/Purchase Metal',
            'description' => 'Calculated purchase amount',
            'is_pk'       => false,
        ],
        [
            'column'      => 'purchase_items.purpose',
            'tag'         => '{{purchase_item.purpose}}',
            'type'        => 'text',
            'group'       => 'Old/Purchase Metal',
            'description' => 'Purpose (Exchange / Purchase)',
            'is_pk'       => false,
        ],

        // ── Order Details ────────────────────────────────────────
        [
            'column'      => 'order_no',
            'tag'         => '{{order_no}}',
            'type'        => 'text',
            'group'       => 'Order',
            'description' => 'Order number',
            'is_pk'       => false,
        ],
        [
            'column'      => 'order_date',
            'tag'         => '{{order_date}}',
            'type'        => 'date',
            'group'       => 'Order',
            'description' => 'Date order was placed',
            'is_pk'       => false,
        ],
        [
            'column'      => 'delivery_date',
            'tag'         => '{{delivery_date}}',
            'type'        => 'date',
            'group'       => 'Order',
            'description' => 'Expected delivery date',
            'is_pk'       => false,
        ],
        [
            'column'      => 'order_adv_amount',
            'tag'         => '{{order_adv_amount}}',
            'type'        => 'number',
            'group'       => 'Order',
            'description' => 'Advance amount paid for order',
            'is_pk'       => false,
        ],
        [
            'column'      => 'order_balance',
            'tag'         => '{{order_balance}}',
            'type'        => 'number',
            'group'       => 'Order',
            'description' => 'Balance due on order',
            'is_pk'       => false,
        ],
        [
            'column'      => '#order_advance_entries ... /order_advance_entries',
            'tag'         => '{{#order_advance_entries}}',
            'type'        => 'loop',
            'group'       => 'Order',
            'description' => 'Loop — iterate order advance entry rows',
            'is_pk'       => false,
        ],
        [
            'column'      => 'order_advance_entries.sno',
            'tag'         => '{{order_item.sno}}',
            'type'        => 'text',
            'group'       => 'Order',
            'description' => 'S.No (inside order loop)',
            'is_pk'       => false,
        ],
        [
            'column'      => 'order_advance_entries.description',
            'tag'         => '{{order_item.description}}',
            'type'        => 'text',
            'group'       => 'Order',
            'description' => 'Item description (inside order loop)',
            'is_pk'       => false,
        ],
        [
            'column'      => 'order_advance_entries.gross_wt',
            'tag'         => '{{order_item.gross_wt}}',
            'type'        => 'number',
            'group'       => 'Order',
            'description' => 'Gross weight (inside order loop)',
            'is_pk'       => false,
        ],
        [
            'column'      => 'order_advance_entries.net_wt',
            'tag'         => '{{order_item.net_wt}}',
            'type'        => 'number',
            'group'       => 'Order',
            'description' => 'Net weight (inside order loop)',
            'is_pk'       => false,
        ],
        [
            'column'      => 'order_advance_entries.mc',
            'tag'         => '{{order_item.mc}}',
            'type'        => 'number',
            'group'       => 'Order',
            'description' => 'Making charge (inside order loop)',
            'is_pk'       => false,
        ],
        [
            'column'      => 'order_advance_entries.rate',
            'tag'         => '{{order_item.rate}}',
            'type'        => 'number',
            'group'       => 'Order',
            'description' => 'Rate per gram (inside order loop)',
            'is_pk'       => false,
        ],
        [
            'column'      => 'order_advance_entries.amount',
            'tag'         => '{{order_item.amount}}',
            'type'        => 'number',
            'group'       => 'Order',
            'description' => 'Item amount (inside order loop)',
            'is_pk'       => false,
        ],
        [
            'column'      => 'order_advance_entries.adv_amount',
            'tag'         => '{{order_item.adv_amount}}',
            'type'        => 'number',
            'group'       => 'Order',
            'description' => 'Advance paid (inside order loop)',
            'is_pk'       => false,
        ],
        [
            'column'      => 'order_advance_entries.balance',
            'tag'         => '{{order_item.balance}}',
            'type'        => 'number',
            'group'       => 'Order',
            'description' => 'Remaining balance (inside order loop)',
            'is_pk'       => false,
        ],

        // ── Repair Details ───────────────────────────────────────
        [
            'column'      => 'repair_no',
            'tag'         => '{{repair_no}}',
            'type'        => 'text',
            'group'       => 'Repair',
            'description' => 'Repair job number',
            'is_pk'       => false,
        ],
        [
            'column'      => 'repair_date',
            'tag'         => '{{repair_date}}',
            'type'        => 'date',
            'group'       => 'Repair',
            'description' => 'Date of repair receipt',
            'is_pk'       => false,
        ],
        [
            'column'      => 'repair_adv',
            'tag'         => '{{repair_adv}}',
            'type'        => 'number',
            'group'       => 'Repair',
            'description' => 'Advance paid for repair',
            'is_pk'       => false,
        ],
        [
            'column'      => 'repair_balance',
            'tag'         => '{{repair_balance}}',
            'type'        => 'number',
            'group'       => 'Repair',
            'description' => 'Balance due on repair',
            'is_pk'       => false,
        ],
        [
            'column'      => '#repair_items ... /repair_items',
            'tag'         => '{{#repair_items}}',
            'type'        => 'loop',
            'group'       => 'Repair',
            'description' => 'Loop — iterate repair item rows',
            'is_pk'       => false,
        ],
        [
            'column'      => 'repair_items.sno',
            'tag'         => '{{repair_item.sno}}',
            'type'        => 'text',
            'group'       => 'Repair',
            'description' => 'S.No (inside repair loop)',
            'is_pk'       => false,
        ],
        [
            'column'      => 'repair_items.description',
            'tag'         => '{{repair_item.description}}',
            'type'        => 'text',
            'group'       => 'Repair',
            'description' => 'Item description (inside repair loop)',
            'is_pk'       => false,
        ],
        [
            'column'      => 'repair_items.gross_wt',
            'tag'         => '{{repair_item.gross_wt}}',
            'type'        => 'number',
            'group'       => 'Repair',
            'description' => 'Gross weight (inside repair loop)',
            'is_pk'       => false,
        ],
        [
            'column'      => 'repair_items.net_wt',
            'tag'         => '{{repair_item.net_wt}}',
            'type'        => 'number',
            'group'       => 'Repair',
            'description' => 'Net weight (inside repair loop)',
            'is_pk'       => false,
        ],
        [
            'column'      => 'repair_items.mc',
            'tag'         => '{{repair_item.mc}}',
            'type'        => 'number',
            'group'       => 'Repair',
            'description' => 'Making charge (inside repair loop)',
            'is_pk'       => false,
        ],
        [
            'column'      => 'repair_items.amount',
            'tag'         => '{{repair_item.amount}}',
            'type'        => 'number',
            'group'       => 'Repair',
            'description' => 'Amount (inside repair loop)',
            'is_pk'       => false,
        ],
        [
            'column'      => 'repair_items.repair_type',
            'tag'         => '{{repair_item.repair_type}}',
            'type'        => 'text',
            'group'       => 'Repair',
            'description' => 'Type of repair (inside loop)',
            'is_pk'       => false,
        ],
        [
            'column'      => 'repair_items.delivery_date',
            'tag'         => '{{repair_item.delivery_date}}',
            'type'        => 'date',
            'group'       => 'Repair',
            'description' => 'Delivery date (inside repair loop)',
            'is_pk'       => false,
        ],

        // ── Chit / Scheme Details ────────────────────────────────
        [
            'column'      => 'total_chit_amount',
            'tag'         => '{{total_chit_amount}}',
            'type'        => 'number',
            'group'       => 'Chit/Scheme',
            'description' => 'Total chit installment amount',
            'is_pk'       => false,
        ],
        [
            'column'      => 'total_chit_benefit',
            'tag'         => '{{total_chit_benefit}}',
            'type'        => 'number',
            'group'       => 'Chit/Scheme',
            'description' => 'Total scheme benefit amount',
            'is_pk'       => false,
        ],
        [
            'column'      => 'chit_closing_wt',
            'tag'         => '{{chit_closing_wt}}',
            'type'        => 'number',
            'group'       => 'Chit/Scheme',
            'description' => 'Closing gold weight for chit',
            'is_pk'       => false,
        ],
        [
            'column'      => '#chit_items ... /chit_items',
            'tag'         => '{{#chit_items}}',
            'type'        => 'loop',
            'group'       => 'Chit/Scheme',
            'description' => 'Loop — iterate chit/scheme rows',
            'is_pk'       => false,
        ],
        [
            'column'      => 'chit_items.sno',
            'tag'         => '{{chit_item.sno}}',
            'type'        => 'text',
            'group'       => 'Chit/Scheme',
            'description' => 'S.No (inside chit loop)',
            'is_pk'       => false,
        ],
        [
            'column'      => 'chit_items.chit_no',
            'tag'         => '{{chit_item.chit_no}}',
            'type'        => 'text',
            'group'       => 'Chit/Scheme',
            'description' => 'Chit/scheme number (inside loop)',
            'is_pk'       => false,
        ],
        [
            'column'      => 'chit_items.scheme_name',
            'tag'         => '{{chit_item.scheme_name}}',
            'type'        => 'text',
            'group'       => 'Chit/Scheme',
            'description' => 'Scheme name (inside loop)',
            'is_pk'       => false,
        ],
        [
            'column'      => 'chit_items.installment_no',
            'tag'         => '{{chit_item.installment_no}}',
            'type'        => 'number',
            'group'       => 'Chit/Scheme',
            'description' => 'Installment number (inside loop)',
            'is_pk'       => false,
        ],
        [
            'column'      => 'chit_items.installment_amt',
            'tag'         => '{{chit_item.installment_amt}}',
            'type'        => 'number',
            'group'       => 'Chit/Scheme',
            'description' => 'Installment amount (inside loop)',
            'is_pk'       => false,
        ],
        [
            'column'      => 'chit_items.paid_months',
            'tag'         => '{{chit_item.paid_months}}',
            'type'        => 'number',
            'group'       => 'Chit/Scheme',
            'description' => 'Months already paid (inside loop)',
            'is_pk'       => false,
        ],
        [
            'column'      => 'chit_items.closing_weight',
            'tag'         => '{{chit_item.closing_weight}}',
            'type'        => 'number',
            'group'       => 'Chit/Scheme',
            'description' => 'Closing gold weight (inside loop)',
            'is_pk'       => false,
        ],
        [
            'column'      => 'chit_items.closing_amount',
            'tag'         => '{{chit_item.closing_amount}}',
            'type'        => 'number',
            'group'       => 'Chit/Scheme',
            'description' => 'Closing amount paid (inside loop)',
            'is_pk'       => false,
        ],
        [
            'column'      => 'chit_items.scheme_benefit',
            'tag'         => '{{chit_item.scheme_benefit}}',
            'type'        => 'number',
            'group'       => 'Chit/Scheme',
            'description' => 'Scheme benefit earned (inside loop)',
            'is_pk'       => false,
        ],
        [
            'column'      => 'chit_items.additional_benefits',
            'tag'         => '{{chit_item.additional_benefits}}',
            'type'        => 'number',
            'group'       => 'Chit/Scheme',
            'description' => 'Additional benefits (inside loop)',
            'is_pk'       => false,
        ],

        // ── Credit Collection ────────────────────────────────────
        [
            'column'      => 'credit_due_amount',
            'tag'         => '{{credit_due_amount}}',
            'type'        => 'number',
            'group'       => 'Credit Collection',
            'description' => 'Outstanding credit due amount',
            'is_pk'       => false,
        ],
        [
            'column'      => 'credit_due_date',
            'tag'         => '{{credit_due_date}}',
            'type'        => 'date',
            'group'       => 'Credit Collection',
            'description' => 'Credit due date',
            'is_pk'       => false,
        ],
        [
            'column'      => 'total_credit_paid',
            'tag'         => '{{total_credit_paid}}',
            'type'        => 'number',
            'group'       => 'Credit Collection',
            'description' => 'Total amount collected so far',
            'is_pk'       => false,
        ],
        [
            'column'      => '#credit_collection_history ... /credit_collection_history',
            'tag'         => '{{#credit_collection_history}}',
            'type'        => 'loop',
            'group'       => 'Credit Collection',
            'description' => 'Loop — iterate credit payment history rows',
            'is_pk'       => false,
        ],
        [
            'column'      => 'credit_collection_history.sno',
            'tag'         => '{{credit_item.sno}}',
            'type'        => 'text',
            'group'       => 'Credit Collection',
            'description' => 'S.No (inside credit loop)',
            'is_pk'       => false,
        ],
        [
            'column'      => 'credit_collection_history.paid_date',
            'tag'         => '{{credit_item.paid_date}}',
            'type'        => 'date',
            'group'       => 'Credit Collection',
            'description' => 'Payment date (inside credit loop)',
            'is_pk'       => false,
        ],
        [
            'column'      => 'credit_collection_history.paid_amount',
            'tag'         => '{{credit_item.paid_amount}}',
            'type'        => 'number',
            'group'       => 'Credit Collection',
            'description' => 'Amount paid (inside credit loop)',
            'is_pk'       => false,
        ],
        [
            'column'      => 'credit_collection_history.payment_mode',
            'tag'         => '{{credit_item.payment_mode}}',
            'type'        => 'text',
            'group'       => 'Credit Collection',
            'description' => 'Payment mode (inside credit loop)',
            'is_pk'       => false,
        ],
        [
            'column'      => 'credit_collection_history.ref_no',
            'tag'         => '{{credit_item.ref_no}}',
            'type'        => 'text',
            'group'       => 'Credit Collection',
            'description' => 'Reference number (inside credit loop)',
            'is_pk'       => false,
        ],

        // ── Sales Return ─────────────────────────────────────────
        [
            'column'      => 'total_return_amount',
            'tag'         => '{{total_return_amount}}',
            'type'        => 'number',
            'group'       => 'Sales Return',
            'description' => 'Total sales return amount',
            'is_pk'       => false,
        ],
        [
            'column'      => 'total_return_gross_wt',
            'tag'         => '{{total_return_gross_wt}}',
            'type'        => 'number',
            'group'       => 'Sales Return',
            'description' => 'Total return gross weight',
            'is_pk'       => false,
        ],
        [
            'column'      => 'total_return_net_wt',
            'tag'         => '{{total_return_net_wt}}',
            'type'        => 'number',
            'group'       => 'Sales Return',
            'description' => 'Total return net weight',
            'is_pk'       => false,
        ],
        [
            'column'      => '#return_items ... /return_items',
            'tag'         => '{{#return_items}}',
            'type'        => 'loop',
            'group'       => 'Sales Return',
            'description' => 'Loop — iterate sales return rows',
            'is_pk'       => false,
        ],
        [
            'column'      => 'return_items.sno',
            'tag'         => '{{return_item.sno}}',
            'type'        => 'text',
            'group'       => 'Sales Return',
            'description' => 'S.No (inside return loop)',
            'is_pk'       => false,
        ],
        [
            'column'      => 'return_items.description',
            'tag'         => '{{return_item.description}}',
            'type'        => 'text',
            'group'       => 'Sales Return',
            'description' => 'Item description (inside return loop)',
            'is_pk'       => false,
        ],
        [
            'column'      => 'return_items.gross_wt',
            'tag'         => '{{return_item.gross_wt}}',
            'type'        => 'number',
            'group'       => 'Sales Return',
            'description' => 'Gross weight (inside return loop)',
            'is_pk'       => false,
        ],
        [
            'column'      => 'return_items.net_wt',
            'tag'         => '{{return_item.net_wt}}',
            'type'        => 'number',
            'group'       => 'Sales Return',
            'description' => 'Net weight (inside return loop)',
            'is_pk'       => false,
        ],
        [
            'column'      => 'return_items.purity',
            'tag'         => '{{return_item.purity}}',
            'type'        => 'text',
            'group'       => 'Sales Return',
            'description' => 'Purity (inside return loop)',
            'is_pk'       => false,
        ],
        [
            'column'      => 'return_items.rate',
            'tag'         => '{{return_item.rate}}',
            'type'        => 'number',
            'group'       => 'Sales Return',
            'description' => 'Rate per gram (inside return loop)',
            'is_pk'       => false,
        ],
        [
            'column'      => 'return_items.amount',
            'tag'         => '{{return_item.amount}}',
            'type'        => 'number',
            'group'       => 'Sales Return',
            'description' => 'Amount (inside return loop)',
            'is_pk'       => false,
        ],
    ];
}
